### ISSUE TITLE
CMake support?

### ISSUE THREAD

**Issue by jon-chuang** [intel/llvm#1000]
Is there any native CMake support for building SYCL projects? Can I just write standard a C++ CMakelists.txt, point to the SYCL Clang compiler and pass it the appropriate flags?

**Comment by AlexeySachkov** [comment]
Hi @jon-chuang, 

> Is there any native CMake support for building SYCL projects?

In intel/llvm no, we don't have any additional CMake modules for building SYCL projects.

> Can I just write standard a C++ CMakelists.txt, point to the SYCL Clang compiler and pass it the appropriate flags?

Yes, this should be enough: you just need to set `CMAKE_CXX_COMPILER` accordingly and pass `-fsycl` as additional command line option.

You can find some helper functions in [codeplaysoftware/computecpp-sdk](https://github.com/codeplaysoftware/computecpp-sdk/blob/master/cmake/Modules/FindComputeCpp.cmake). The won't work with intel/llvm compiler and if I understand correctly, they allow you to perform separate compilation of host and device code (but I might be wrong, just briefly looked in there)

Please let us know if you find these helper functions interesting - since we also have support for separate and ahead-of-time compilation it might be good to have similar helpers for our compiler too.

**Comment by AlexeySachkov** [comment]
I think that answers to original questions were provided and we can close this issue. There were no extra requests and therefore there are no further actions we can take.

I also found that there is official oneAPI documentation about [how to use CMake with DPCPP compiler](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-setup/use-the-command-line/use-cmake-with-the-compiler.html).
