### ISSUE TITLE
naming question for work_group_local

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#10182]
Could the name "sycl::ext::oneapi::experimental::work_group_local" be reduced to "sycl::ext::oneapi::experimental::local" ?  

In CUDA and HIP, the name is simply "__shared__".

**Comment by AlexeySachkov** [comment]
Tagging @Pennycook here to reply

**Comment by Pennycook** [comment]
I don't think this is a good idea.

We deliberately aligned with C++'s naming of `thread_local` here, to simplify teaching. The idea is that if somebody understands how thread-local variables are created with `thread_local`, they should be able to understand how work-group-local variables are created with `work_group_local`.

I can see the appeal of using a short name like `local`, but it's not clear from the name what the variable is actually local to.  `work_group_local` is very clear, and leaves the door open to variables that are local to different types of group (e.g. `sub_group_local`).

If the name change suggested here is primarily due to the verbosity of nested namespaces, you can view them as temporary.  Once the extension's design is settled it will become `sycl::ext::oneapi::work_group_local`; if the extension is accepted to a future SYCL standard, it would become `sycl::work_group_local`.

**Comment by jinz2014** [comment]
"local_accessor" is commonly used by users/developers. I think we could have a single name ("local").

**Comment by AlexeySachkov** [comment]
Note that you can always have an alias to reduce the verbosity and adjust the name, if you want to: [cppreference: Type alias, alias template](https://en.cppreference.com/w/cpp/language/type_alias):

```c++
template<typename T>
using local = sycl::ext::oneapi::experimental::work_group_static<T>;
// work_group_local was renamed to work_group_specific and then to work_group_static
// The latter seems to be the final version (?)
```

Considering the reply above from John, I will close this question as answered/resolved. The implementation of the extension is in progress (#15061). Once we have it and have some hands-on experience with it, we can see if we need to reconsider the name once again.
