### ISSUE TITLE
clangd fails on basic code examples

### ISSUE THREAD

**Issue by JPenuchot** [intel/llvm#11088]
**Describe the bug**

The clangd executable provided in the Intel OneAPI Basekit crashes on basic SYCL example.

**To Reproduce**

Run an editor configured to run the clangd executable from Intel OneAPI Basekit and paste any of the examples from one of this documentation page: https://intel.github.io/llvm-docs/GetStartedGuide.html.

**Environment (please complete the following information):**

- OS: Arch Linux
- Target device and vendor: Intel iGPU (i5 6300U)
- DPC++ version: 2023.2.0

**Additional context**

In my specific case, I've been using the Kate editor with the following config:

```json
        "c": {
            "command": ["/opt/intel/oneapi/compiler/2023.2.0/linux/bin-llvm/clangd", "-log=error", "--background-index", "--limit-results=500", "--completion-style=bundled"],
            "commandDebug": ["clangd", "-log=verbose", "--background-index"],
            "url": "https://clang.llvm.org/extra/clangd/",
            "highlightingModeRegex": "^(C|ANSI C89|Objective-C)$"
        },
        "cpp": {
            "use": "c",
            "highlightingModeRegex": "^(C\\+\\+|ISO C\\+\\+|Objective-C\\+\\+)$"
        }
```

The environment variables were properly set using `setvars.sh`, and here's the error log: [error.txt](https://github.com/intel/llvm/files/12538839/error.txt)

**Comment by LXYan2333** [comment]
I found the same issue in my Debian 12. I'm using CMake (following [this guide](https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2023-2/use-cmake-with-the-compiler.html)) and vscode to try the sycl basic example.

The official clangd will complain about the `-ipo` compile option and a lot of other errors (failed to found header file, no matching construction function etc), so I try to use the clangd packed with the dpc++ compiler: `/opt/intel/oneapi/compiler/latest/linux/bin-llvm/clangd`, but it keeps crashing while parsing AST.

After some test, this problem seems related to the `-fsycl` compile option. Edit `build/compile_commands.json` and remove the `-fsycl` compile option, then the dpc++ clangd finally works as expected.

My workaround is to create a CMakePresets.json in the workspace root directory with 2 cmake presets: one used to generate the `build/compile_commands.json` by manually set include directory

```
target_include_directories(sycl_test PRIVATE /opt/intel/oneapi/compiler/latest/linux/include PRIVATE /opt/intel/oneapi/compiler/latest/linux/include/sycl)
```

another option is used to compile the target:
```
find_package(IntelSYCL REQUIRED)
add_sycl_to_target(TARGET sycl_test SOURCES sycl_test.cc)
```

or you can manually edit `compile_commands.json` and remove all the `-fsycl` flag.

**Comment by LXYan2333** [comment]
maybe related to https://github.com/clangd/clangd/issues/1097
