### ISSUE TITLE
sycl-for-cuda causes build error

### ISSUE THREAD

**Issue by varsha-madananth** [intel/llvm#1124]
We have been experimenting with sycl-for-cuda this week. We experienced couple of issues over this week. To summarize-
1. On 02/10 - Successful build of sycl-for-cuda. However, when running the executable generated for nvidia target , results in -
what():  OpenCL API failed. OpenCL API returns: -30 (CL_INVALID_VALUE) -30 (CL_INVALID_VALUE)
which is strange because as per the blogpost below you do not need OpenCL for running on nvidia.
https://www.codeplay.com/portal/02-03-20-codeplay-contribution-to-dpcpp-brings-sycl-support-for-nvidia-gpus.
Please correct me if my understanding is wrong.

2. On 02/11 - Unsuccessful build (see attached logs). Looks like there was an attempt made to fix the issue by changing the call from  CL to PI as per git history. But it is not fixed completely, as it gives build errors. I just wanted to bring this to the developers notice. In case, it is being fixed, please let us know and if we are missing something here. 

Thanks,
Varsha
[builderror0211.txt](https://github.com/intel/llvm/files/4194340/builderror0211.txt)

[simplesyclapplogs.txt](https://github.com/intel/llvm/files/4194664/simplesyclapplogs.txt)

**Comment by fwyzard** [comment]
Hi @varsha-madananth ,

the build error you report should be fixed by now.
The `cuda-dev` should build fine by itself, but if you try to merge it with the HEAD of the `sycl` branch, you also need the fix in codeplaysoftware/sycl-for-cuda#4 .

About the runtime error, did you set the plugin according to the instructions on the blog
```
SYCL_BE=PI_CUDA sycl-app.exe
```
?
I haven't been able to test it myself, my sample application still does not compile for CUDA :-(

**Comment by Ruyk** [comment]
We are working on cuda-dev to update the branch to the latest changes on the sycl branch. Currently, the main issue that is dragging us back is the changes to the PI plugin mechanism, which can now support multiple backends at the same time. That is great, because the environment variable is not needed and you could use OpenCL and CUDA on the same application, but we need to check all lit tests that are now running on multiple backends to make sure nothing is broken.

**Comment by Ruyk** [comment]
@varsha-madananth  Do you still have problems building the CUDA support now that it has been merged in the `sycl` branch?

**Comment by varsha-madananth** [comment]
@Ruyk We are now able to build sycl apps on nvidia hardware. thank you

**Comment by Ruyk** [comment]
Thanks!
@bader  I believe this can be closed now then

**Comment by bader** [comment]
Fixed by #1091.
