### ISSUE TITLE
workflow for adapters

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#11620]
I suppose that the unified runtime is an integral part of the SYCL compiler. It is now moved to a separate github repository. People (users) who are not familiar with the separation may modify a file in “sycl/plugins/unified_runtime/ur/adapters/hip” for adding a new feature, but the file originates from another repository.  This may be very confusing for testing and making a pull request. 

Can you please suggest the workflow for updating a file in the “hip” directory ?

**Comment by AlexeySachkov** [comment]
Tagging @kbenzie here to help answer the question

**Comment by al42and** [comment]
https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html#adapter-change-process has a description of the new process

**Comment by kbenzie** [comment]
Hi @jinz2014, as @al42and pointed out the [Unified Runtime Adapter Change Process](https://oneapi-src.github.io/unified-runtime/core/CONTRIB.html#adapter-change-process) details the current guidance for making changes to the adapters.

This is a new process and we are still in the process of refining it. Please let use know if there are any gaps so we can make improvments.

> People (users) who are not familiar with the separation may modify a file in “sycl/plugins/unified_runtime/ur/adapters/hip” for adding a new feature, but the file originates from another repository. This may be very confusing for testing and making a pull request.

There was a short period of time where the source code for the hip adapter existed in both [intel/llvm](https://github.com/intel/llvm) and in [oneapi-src/unified-runtime](https://github.com/oneapi-src/unified-runtime) but as of #11343 the source files for the hip adapter are no longer present in [intel/llvm](https://github.com/intel/llvm) and are instead fetched from [oneapi-src/unified-runtime](https://github.com/oneapi-src/unified-runtime). There should now be a single source of truth for the hip adapter [here](https://github.com/oneapi-src/unified-runtime/tree/adapters/source/adapters/hip).

**Comment by kbenzie** [comment]
>  2. Copy the modified file to the intel/llvm/***/hip/adapters/

@jinz2014 this should never be needed. by default intel/llvm uses [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) to pull the revision specified by the [UNIFIED_RUNTIME_TAG](https://github.com/intel/llvm/blob/sycl/sycl/plugins/unified_runtime/CMakeLists.txt#L57-L63). We recently added the ability to override the default CMake behaviour to make local development easier. That's described in [Build DPC++ toolchain with a custom Unified Runtime](https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-a-custom-unified-runtime).

Instead of step 2. I would clone the UR repo when in the `sycl/plugins/unified_runtime` subdirectory of intel/llvm and set `-DSYCL_PI_UR_USE_FETCH_CONTENT=OFF` so that CMake will then `add_subdirectory()` the local clone of the UR repo:

```console
$ cd inte/llvm
$ pushd sycl/plugins/unified_runtime
$ git clone https://github.com/oneapi-src/unified-runtime -b adapters
$ popd
$ python buildbot/configure.py -o build-with-local-ur --hip \
    --cmake-opt=-DSYCL_PI_UR_USE_FETCH_CONTENT=OFF
$ ninja -C build-with-local-ur
```

**Comment by jinz2014** [comment]
Thanks!
