### ISSUE TITLE
Suggest the migration from get_pointer() to get_multi_ptr()

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#12057]
Why is "get_pointer()" deprecated ?  Could you please recommend how to migrate from "get_pointer()" to "get_multi_ptr()" for a SYCL (local) accessor ?

I also noticed that quite a few E2E tests still call "get_pointer()". 

Thanks.

**Comment by ikabadzhov** [comment]
This is a similar issue https://github.com/KhronosGroup/SYCL-Docs/issues/424. Depending on the use case, the direct substitution for now seems to be either `get_multi_ptr<sycl::access::decorated::no>()`, `get_multi_ptr<sycl::access::decorated::yes>()` or `get_multi_ptr<sycl::access::decorated::legacy>()`.

**Comment by zjin-lcf** [comment]
Could you please clarify the use case for decorated::yes and docorated::no ?  Thanks.

**Comment by steffenlarsen** [comment]
@ikabadzhov is right. The right replacement here is `get_multi_ptr<...>`. As to the difference between `decorated::yes` and `decorated::no`, the primary difference is the type returned by `get()`. For `decorated::yes` is is the same as `get_decorated()` and for `decorated::no` it is the same as `get_raw()`. Behind the scenes, the representation is the same, but I personally prefer `decorated::no` unless there's a reason to have decorated address from `get()`.

**Comment by AlexeySachkov** [comment]
> @ikabadzhov is right. The right replacement here is `get_multi_ptr<...>`. As to the difference between `decorated::yes` and `decorated::no`, the primary difference is the type returned by `get()`. For `decorated::yes` is is the same as `get_decorated()` and for `decorated::no` it is the same as `get_raw()`. Behind the scenes, the representation is the same, but I personally prefer `decorated::no` unless there's a reason to have decorated address from `get()`.

With `decorated::yes` compiler may insert some extra implementation-defined metadata to explicitly highlight the address space of a pointer. This could help device compilers/backends with optimizations. However, there are no generic guidelines about which to choose, because it is highly dependent on the exact backend and application, i.e. whether or not backend address space inference functionality is good enough so that you can ignore decorated pointers, or bad enough so that you have to use decorated pointers.

I assume that the question was answered, so I will close the issue, but please feel free to comment/re-open, or open a new one in case of further questions.
