### ISSUE TITLE
dpc++ for Huawei Ascend?

### ISSUE THREAD

**Issue by SetoKaiba** [intel/llvm#12136]
https://www.oneapi.io/blog/huawei-extends-dpc-with-support-for-its-ascend-ai-chipset/
I saw this. But it seems that I can't find any other info about it. Is it supported?

**Comment by AlexeySachkov** [comment]
Hi @SetoKaiba,

We do not have that plugin at `intel/llvm`. Looking at [the slides](https://www.iwocl.org/wp-content/uploads/15-iwocl-syclcon-2021-maghaerh.pdf) it seems like it hadn't been upstreamed by the time they presented it, see last slide:

> Will be looking forward to upstream our work

It may or may not have happened since then and even if it did, they upstreamed it to a separate repo. I would suggest to try and contact project authors to ask them about the status
