### ISSUE TITLE
Warning or error message when invalid value for -fsycl-device-obj ?

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#12159]
For the following command,

clang++  -std=c++17  -fsycl -fsycl-targets=nvptx64-nvidia-cuda main.cpp -fsycl-device-only -fsycl-device-obj=test -S

No warning or error is reported, but the compiler's help message shows

  -fsycl-device-obj=<value>
                          Specify format of device code stored in the resulting object. Valid values are: spirv, llvmir (default)

**Comment by maarquitos14** [comment]
I have quickly looked into it and it seems that if the value is not `spirv`, we simply fall back to the default (llvmir). Since this is related to driver, I think @mdtoguchi should be able to help here: would it be reasonable to emit a warning like "Invalid value for `-fsycl-device-obj`, falling back to default (llvmir)"?. Personally, I think an error is too much, but a warning might be reasonable.

**Comment by mdtoguchi** [comment]
I would agree that emitting a warning on a bad value is reasonable and informing the user that 'llvmir' would be used.

**Comment by jinz2014** [comment]
I reported the issue after trying #10801 which does not seem to generate PTX codes. Yes, warning is very reasonable. Thanks.

**Comment by mdtoguchi** [comment]
This has been addressed here:  https://github.com/intel/llvm/commit/81a9060831273f92e1dc2e310b233d98fb9dc367
