### ISSUE TITLE
Aspect for bfloat16

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#12196]
Could  aspect::ext_oneapi_bfloat16_math_functions simply be aspect::bfloat16 ?

It seems that the bfloat16 is not available on Nvidia V100 GPUs after running the test program "aspects.cpp". 

    if (plt.has(aspect::ext_oneapi_bfloat16_math_functions)) {
      std::cout << " ext_oneapi_bfloat16_math_functions" << std::endl;
    }

**Comment by hdelan** [comment]
Hi @jinz2014 so the following works in SYCL for GTX1050:
```c++
#include <sycl/sycl.hpp>

using T = float;

int main() {
  sycl::queue q;
  auto ptr = sycl::malloc_shared<T>(1, q);
  ptr[0] = 0;
  q.single_task([=] {
     sycl::ext::oneapi::bfloat16 bf1{3}, bf2{2};
     ptr[0] = bf1 + bf2;
   }).wait();
  printf("Got device global: %f\n", ptr[0]);
}
```
So you should have emulated support for basic bfloat16 stuff on any SYCL device. However it seems that NVidia doesn't support bfloat16 for V100 GPUs. See the thread here https://github.com/salesforce/LAVIS/issues/91

In SYCL if I change the kernel to:
```
ptr[0] = bf1 + sycl::sin(bf2);
```
Then compilation fails for my old GPU (GTX1050). Because even though we can emulate support for bfloat16 in SYCL, we do not have implementations for bfloat16 math funcs since they are not provided by NVidia.

**Comment by jinz2014** [comment]
Hi @hdelan Thank you for the examples and descriptions.
