### ISSUE TITLE
Align terminology used by ONEAPI_DEVICE_FILTER and SYCL_DEVICE_ALLOWLIST

### ISSUE THREAD

**Issue by uditagarwal97** [intel/llvm#12632]
Currently, SYCL_DEVICE_ALLOWLIST uses 'acc' to select accelerator device type while ONEAPI_DEVICE_FILTER uses 'fpga' for the same.  I propose that we also update SYCL_DEVICE_ALLOWLIST  to use 'fpga' instead of 'acc'. Not only this will make the terminology consistent, it will also simplify the code as some functions are common between SYCL_DEVICE_ALLOWLIST and ONEAPI_DEVICE_FILTER .

**Comment by uditagarwal97** [comment]
@aelovikov-intel @gmlueck thoughts?

**Comment by aelovikov-intel** [comment]
\+ @steffenlarsen @sergey-semenov

**Comment by steffenlarsen** [comment]
I think this is a reasonable idea, but maybe we should just allow both? The reason we use `acc` is because it is one of the 4 device types in SYCL: `cpu`, `gpu`, `accelerator` and `custom` (ignoring `host`, `automatic` and `all`). Since `ONEAPI_DEVICE_SELECTOR` isn't SYCL-specific, we do not have full control over it, so picking accelerator devices when `fpga` is specified is something we will have to live with, but `SYCL_DEVICE_ALLOWLIST` is, as the name suggests, SYCL specific, so I would prefer we at least let users use SYCL terminology if they intend to use it.

**Comment by gmlueck** [comment]
OK with me.
