### ISSUE TITLE
[SYCL][CUDA][BUILD] cuPTI error while building the compiler with CUDA backend

### ISSUE THREAD

**Issue by TejaX-Alaghari** [intel/llvm#12710]
**Bug Description**
Build failure while compiling **unified-runtime-src\source\adapters\cuda\tracing.cpp**

**To Reproduce**
python .\llvm\buildbot\configure.py --cuda -o /path/to/install/dir
python .\llvm\buildbot\compile.py -o /path/to/install/dir

**Environment:**

- OS: Windows 10
- Target device and vendor: Nvidia GPU
- Dependencies version: CUDA Toolkit - 12.0 or 12.3

**Additional Context**
Complete error log: [LLVM_CUDA_win10_build_log.txt](https://github.com/intel/llvm/files/14274989/LLVM_CUDA_win_build_log.txt)

**Comment by rafbiels** [comment]
The issue is all the function pointer typedefs here:
https://github.com/oneapi-src/unified-runtime/blob/main/source/adapters/cuda/tracing.cpp
are of the format:
```cpp
using foo_fn = CUPTIAPI CUptiResult (*)(args);
```
but should be of the format:
```cpp
using foo_fn = CUptiResult (CUPTIAPI *)(args);
```

because `CUPTIAPI` expands to `__stdcall` on Windows and this needs to be placed after the return type. There is an example of a function pointer typedef in the [`__stdcall` docs](https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170#example).

Here's a proof the other syntax should work: https://godbolt.org/z/Pd3Ess79G

I don't currently have a Windows machine to test the fix in a full build, so I'd prefer someone who can test it makes a PR. Tagging @kbenzie for UR.

**Comment by kbenzie** [comment]
Tagging @npmiller who's team owns the CUDA adapter.

**Comment by TejaX-Alaghari** [comment]
I have tested the suggestion on Win 10 with 12.0 toolkit and I can confirm it works.

Thanks @rafbiels
