### ISSUE TITLE
Invalid device::backend_version when querying device on Windows

### ISSUE THREAD

**Issue by mmoadeli** [intel/llvm#14157]
### Describe the bug

Below code built using `clang.exe   -fsycl -fsycl-targets=nvidia_gpu_sm_75` on Windows with `GTX 1650` prints `3.0` while `7.5` expected.
```
#include "sycl/sycl.hpp"
#include <iostream>

int main() {
  sycl::queue Q;
  std::cout << Q.get_device().get_info<sycl::info::device::backend_version>() << std::endl;
  return 0;
};
```
The same code works fine on Ubuntu.

### To reproduce

`clang.exe   -fsycl -fsycl-targets=nvidia_gpu_sm_75 code.cpp`

### Environment

OS: Windows
Target: CUDA

**Comment by JackAKirk** [comment]
This caused by the opencl gpu being selected instead of the cuda one, even if the nvptx64 triple is specified by the compilation. This can be "fixed" by either setting

```
set ONEAPI_DEVICE_SELECTOR=cuda:gpu
```

or by including a kernel that can only be compiled with the cuda backend.


Arguably cuda gpus should be preferred in the device selector ahead of opencl gpu ones (but not level_zero); but other may have a different opinion.

**Comment by mmoadeli** [comment]
Thank you @JackAKirk 
I close the issue
