### ISSUE TITLE
[SYCL][E2E] Likely aspect-ext_intel_free_memory is ignored

### ISSUE THREAD

**Issue by KornevNikita** [intel/llvm#14244]
### Describe the bug

Looks like we're overlooking `aspect-ext_intel_free_memory` while running SYCL E2E tests.
`sycl-ls --verbose` prints this aspect only if `ZES_ENABLE_SYSMAN=1` is set, like: `ZES_ENABLE_SYSMAN=1 sycl-ls --verbose`
Thus we never run the [test](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Plugin/level_zero_device_free_mem.cpp) requiring this aspect. I'm not sure if it's a good idea to just add this variable to the script checking the aspects, so wanted to discuss it.

**Comment by KornevNikita** [comment]
@intel/dpcpp-devops-reviewers FYI

**Comment by AlexeySachkov** [comment]
> I'm not sure if it's a good idea to just add this variable to the script checking the aspects, so wanted to discuss it.

I don't like aspects which depend on env variables, that is somewhat bad design, I think. We could rewrite the test *not* to have `REQUIRES` and just do dynamic aspect check + early exit, but it goes against our philosophy of actually reporting which tests were run and which weren't.

Of course, its easy to make a mistake and forget to add the env variable to a test so that the feature is actually available when it is run, but I still think that it is better than not running the test at all. Mismatch should be easy to detect and fix and therefore I suggest that we run `sycl-ls --verbose` under `ZES_ENABLE_SYSMAN=1` environment to get all possible aspects and avoid skipping tests unnecessarily.

**Comment by DYNIO-INTEL** [comment]
Since https://github.com/oneapi-src/unified-runtime/commit/27ad3f7d95a4e78e10c31df0e5c73afe549d1449 `SYSMAN` should be enabled by default
