### ISSUE TITLE
The "bool" data type support by atomic_ref 

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#14412]
What about the "bool" data type for the sycl::atomic_ref class ?

**Comment by jinz2014** [comment]
I am not clear if there will be challenges for implementing atomic operations over lower bits (1,2,4,8, etc).  Okay.

**Comment by AlexeySachkov** [comment]
> I am not clear if there will be challenges for implementing atomic operations over lower bits (1,2,4,8, etc). Okay.

Could you please clarify which operations you are interested in? I don't quite understand why do you care for specific bits, because C++ spec does not define `sizeof(bool)`, nor it defines it internal representation, i.e. `true` could be represented as 8-byte integer containing constant `7` and that will be a valid implementation.

**Comment by jinz2014** [comment]
When sizeof(bool) is not defined in C++, does it mean atomic operations over bool will not be supported by atomic_ref ?

**Comment by AlexeySachkov** [comment]
> When sizeof(bool) is not defined in C++, does it mean atomic operations over bool will not be supported by atomic_ref ?

That would be the main obstacle here, right. If `sizeof(bool)` matches an already supported type, then we can simply make `atomic_ref<bool>` an alias to `atomic_ref<T>`, or something close to it. However, if `sizeof(bool) == 1`, for example, then we are in trouble, because there may not be 1-byte atomics support on a device and we can't internal extend the value, because we only have a reference to a user-provided value and by expanding it we will corrupt some of users data (either stack or heap).
