### ISSUE TITLE
libdevice code clean-up

### ISSUE THREAD

**Issue by bader** [intel/llvm#1546]
We need to set the single name for the library located here: and use this unified name to name the directory, cmake target, functions.
Today we use 
- `libsycldevice` as CMake target name.
- `devicelib` as function prefix
- `libdevice` directory name

It also should probably specify that it's for SPIR devices only.

**Comment by asavonic** [comment]
@bader, @vzakhari 
I'm not sure why the directory is called `libdevice` now, it used to be `devicelib` to match the functions prefix. Does it make sense to rename it back? I'm hesitant to rename the functions instead, because it is a part of the API now.

**Comment by vzakhari** [comment]
I just followed the naming convention for top-level library projects, that is why I named the directory libdevice.  I do not see big problem in having project directory named lib* and using devicelib prefix for the function names.

I suggest naming the library libspirdevice.  If we find a convenient way for combining SYCL and OMP parts into one library, then we can have the same libspirdevice CMake target, otherwise, I suggest using libspirsycldevice and libspirompdevice CMake targets.

**Comment by bader** [comment]
`libspirdevice` seems quite reasonable. It's more common to use `lib` as a prefix than as a post-fix.

> I'm hesitant to rename the functions instead, because it is a part of the API now.

What API do you mean here? I was under impression that it's an internal API and not outside of this project, so we should be able to update all uses of this API, right?
If so we can discuss if it function prefix can be renamed to align with the library name. (e.g. `__spir_device_`).

**Comment by vzakhari** [comment]
I think Andrew means that `_devicelib_` prefix is already documented here https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/C-CXX-StandardLibrary/DeviceLibExtensions.rst and probably as OpenCL extensions as well.

**Comment by asavonic** [comment]
> not outside of this project, so we should be able to update all uses of this API, right?

It is expected that device backends implement this API outside of this project. I don't think that rename is justified: if nobody asked about this during code review, then it doesn't sound critical and worth changing.
