### ISSUE TITLE
[SYCL] gpu_selector not failing when no GPU devices

### ISSUE THREAD

**Issue by jbrodman** [intel/llvm#1679]
```
 cl::sycl::queue queue(cl::sycl::gpu_selector{});
  std::cout << "Running on " << queue.get_device().get_info<cl::sycl::info::device::name>() << std::endl;
```

on a CPU system prints either:
```
./test1
Running on Intel(R) FPGA Emulation Device
```
or
```
env SYCL_DEVICE_TYPE=CPU ./test1
Running on Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
```

I think it's supposed to be throwing an exception if there's not an available GPU device...

**Comment by KarachunIvan** [comment]
I reckon that you observe such behavior because of this line:
https://github.com/intel/llvm/blob/44954afb3aa6b492a1c77e97f0763385e9ba98d9/sycl/source/device_selector.cpp#L55

`gpu_selector` return -1 for every device except for GPU. So `dev_score` will be `-1` (`score = -1` by default). Besides, `isDeviceOfPreferredSyclBe` returns `true` if the device uses opencl backend.
So, in that case first OpenCL device will be chosen.

**Comment by jbrodman** [comment]
Probably.

It's still violating the spec. :)

**Comment by Ruyk** [comment]
I found this problem too while working on NVIDIA OpenCL filtering, i'll fix it as part of that patch

**Comment by Ruyk** [comment]
In https://github.com/intel/llvm/pull/1689 , devices with score -1 are properly discarded

**Comment by romanovvlad** [comment]
Will put a fix on review soon.

**Comment by romanovvlad** [comment]
Should be resolved by https://github.com/intel/llvm/pull/1689. @jbrodman please, check.

**Comment by jbrodman** [comment]
Looks like it now properly fails.
