### ISSUE TITLE
Execution delayed with OpenCL GPU

### ISSUE THREAD

**Issue by GDanii** [intel/llvm#1869]
Hi!

While experimenting with the OneAPI I noticed an interesting behavior when I execute kernels on GPU using the OpenCL plugin. The execution seems to start only when a call is made on the returned event. I am using the beta6 release as a Docker container on Ubuntu 18.04, but I experienced the same behavior with beta6 on Windows as well.

Using the following simplified application, that spins for 10 seconds after submission, and 5 seconds into this spin loop starts to print the execution status in every second:

```C++
#include <CL/sycl.hpp>
#include <chrono>
namespace sycl = cl::sycl;
int main() {
	sycl::queue queue(sycl::default_selector(), sycl::property_list{sycl::property::queue::enable_profiling()});
	std::cout << "Running on " << queue.get_device().get_info<cl::sycl::info::device::name>() << std::endl;
	
	auto wall_clock_start = std::chrono::steady_clock::now();
	auto event = queue.submit([&](sycl::handler &cgh) {
		cgh.single_task([=]() {});
	});
	
	std::cout << "Start delay loop \n";
	auto t1 = std::chrono::steady_clock::now();
	int status_printed = 0;
	while(true) {
		std::chrono::duration<double> e = std::chrono::steady_clock::now()-t1;
		if(e.count() > 5 && status_printed < (int)e.count()) {
			auto status = event.get_info<cl::sycl::info::event::command_execution_status>();
			std::cout << (int)status << std::endl;
			status_printed = (int)e.count();
		}
		if(e.count() > 10)
			break;
	}
	std::cout << "End delay loop \n";
	
	event.wait();
	
	std::chrono::duration<double> elapsed_seconds = std::chrono::steady_clock::now()-wall_clock_start;
	cl_ulong time_submit = event.get_profiling_info<sycl::info::event_profiling::command_submit>();
	cl_ulong time_start = event.get_profiling_info<sycl::info::event_profiling::command_start>();
	cl_ulong time_end =event.get_profiling_info<sycl::info::event_profiling::command_end>();
	std::cout << "Event submission: " << (time_start - time_submit) / 1e6 << " ms; execution: " << (time_end - time_start) / 1e6 << " ms; wall clock: " << elapsed_seconds.count()*1000 << " ms\n";
}
```

The results are the following:

SYCL_DEVICE_TYPE=GPU SYCL_BE=PI_OPENCL ./a.out
```
Running on Intel(R) Gen9 HD Graphics NEO
Start delay loop
2
0
0
0
0
0
End delay loop
Event submission: 5001.89 ms; execution: 0.003583 ms; wall clock: 10094.5 ms
```

SYCL_DEVICE_TYPE=GPU SYCL_BE=PI_LEVEL0 ./a.out
```
Running on Intel(R) Gen9
Start delay loop
0
0
0
0
0
0
End delay loop
Event submission: 0.072791 ms; execution: 0.009877 ms; wall clock: 10106.6 ms
```

SYCL_DEVICE_TYPE=CPU ./a.out
```
Running on Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
Start delay loop
0
0
0
0
0
0
End delay loop
Event submission: 0.091819 ms; execution: 0.005946 ms; wall clock: 10069.5 ms
```

With OpenCL on GPU the kernel only starts executing when the _event.get_info_ is called after 5 seconds. If I simply spin for 10 seconds without calling _event.get_info_, then the submission time becomes 10 seconds (when the _wait_ is called).

Interestingly, the issue seems to disappear if VTune is attached, as if it would trigger the execution. Based on looking at when the spike appears in GPU usage with standard system monitoring tools it looks that the execution is really delayed and the profiling info returned from the event is correct.

**Comment by alexbatashev** [comment]
Hi @GDanii 

Here's an extract from [OpenCL Specification](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/pdf/OpenCL_API.pdf) section 3.2.2:

> Once these conditions are met, the kernel-instance is launched and the work-groups associated
with the kernel-instance are placed into a pool of ready to execute work-groups. This pool is called
a work-pool. The work-pool may be implemented in any manner as long as it assures that workgroups placed in the pool will eventually execute.

My interpretation is that OpenCL implementation may delay kernel execution for as long as it needs. The only condition is that the kernel must be eventually executed. So, what you observe is an implementation detail, rather than a bug.

On the other hand, L0 forces commands to be executed immediately (see [here](https://spec.oneapi.com/level-zero/latest/core/PROG.html#command-queues)):

> Command lists submitted to a command queue are immediately executed in a fifo manner.

And that is what your experiment proves.

**Comment by romanovvlad** [comment]
I guess that we can "avoid" delaying but calling clFlush after command enqueuing

**Comment by GDanii** [comment]
Thanks @alexbatashev for the detailed reply! I didn't do extensive testing on this, but my assumption is that the execution will only start if something triggers it, like a call on the related event. I think it is questionable if this counts as 'eventual', maybe yes. 

In any case, I think from API usage point of view it is strange that I submit something for _asynchronous_ execution, but it may only start to execute once I touch the returned event. In most of the cases I guess implicit or explicit waiting on the event will trigger the execution resulting in actually more of a synchronous behavior. Finally, this being inconsistent between devices further complicates the picture. In my opinion the flush, suggested by @romanovvlad, sounds to be a reasonable extension.

**Comment by keryell** [comment]
@GDanii perhaps the GPU is busy with some more important stuff, such as displaying the screen?
I agree that the concept of best effort should be more carefully designed or at least configurable... Perhaps it is a parameter of the OpenCL stack or driver?
Otherwise in SYCL you can already achieve this by waiting on the queue. Of course, since you do not want to block, you can put this in an eager  `std::async` to do the `queue::wait()` in the background... :-)
