### ISSUE TITLE
[SYCL][SUBGROUPS] Non-integral types incompatible with sg.load()

### ISSUE THREAD

**Issue by jasonsewall-intel** [intel/llvm#1916]
Issue: 
subgroup.load fails for non-integral types like float and double. Using bit_cast seems to fail too.

Expected behavior:

load shouldn't care about the data type, just the width.

    auto vals = ;// read-capable access to buffer of doubles
    const int o = ;// some positive integer
    const double v = sg.load<1>(vals.get_pointer()+o);

Details:

I would expect bit_cast to work here, but it does not:

    const double v = detail::sub_group::bit_cast<const double>(sgr.load<1>(detail::sub_group::bit_cast<multi_ptr<unsigned long, access::address_space::global_space>>(vals.get_pointer()+o)));

**Comment by Pennycook** [comment]
https://github.com/intel/llvm/commit/fe8d852d323e1edaae7abf04390280f423876044 just added support for 64-bit sub-group loads/stores.  I'm still looking into what we should do for user-defined types, but `float` and `double` should work now.

**Comment by AlexeySachkov** [comment]
The most up-to-date [spec](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_group_load_store.asciidoc) on `sub_group::load<T>()` says that `T` must be a [`NumericType`](https://en.cppreference.com/w/cpp/named_req/NumericType) and it looks like our implementation supports it since #1031.

At least I'm able to compile the following snippet just fine:
```
SYCL_EXTERNAL void foo(nd_item<1> it, bar *ptr) {
  auto sg = it.get_sub_group();
  auto val = sg.load<bar>(ptr);
}
```

I will close this one assuming that it is fixed, but we should probably extend our [test](https://github.com/intel/llvm-test-suite/blob/intel/SYCL/SubGroup/load_store.cpp) to get this case covered
