### ISSUE TITLE
[SYCL] 'CL_OUT_OF_RESOURCES' while using 'max_work_group_size'

### ISSUE THREAD

**Issue by FredrikErikJohansson** [intel/llvm#2075]
I'm running a reduction kernel and I want to use the maximum available work group size as the local range. The code works perfectly using a GPU (GeForce GTX 1660 SUPER) but when running on a CPU (Intel Core i7-9700K) the program crashes with the error code (CL_OUT_OF_RESOURCES). However, if I use half or less of the maximum work group size, `size_t local = std::min(
      height * width,
      device.get_info<cl::sycl::info::device::max_work_group_size>()/2);`, the code works. What could be the cause of this issue?

```
#include <iostream>
#include <fstream>
#include <string>
#include <algorithm>
#include <stdlib.h>

#include "../headers/extreme_dsm_dtm.hpp"

#include <opencv2/core/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>
#include <CL/sycl.hpp>

int main() {
   size_t width;
   size_t height;
   sycl::default_selector device_selector;
   sycl::queue queue(device_selector);
   auto device = queue.get_device();
   std::cout << "Running on: "
               << device.get_info<sycl::info::device::name>()
               << "\n";

   std::vector<cv::String> dhm_path;
   cv::glob("../dhm/*.tif", dhm_path, true);
   std::vector<cv::Mat> dhm_images;
   std::vector<sycl::range<1>> range_images;
   for (size_t i=0; i < dhm_path.size(); i++) {
      dhm_images.push_back(imread(dhm_path[i], cv::IMREAD_UNCHANGED));
      width = dhm_images[i].cols;
      height = dhm_images[i].rows;
      range_images.push_back(sycl::range<1>(height * width));
   }

   for(size_t i = 0; i < dhm_images.size(); i++) {
      int percent = 100*(double)i/(double)dhm_images.size();
      std::cout << percent << "%\r" << std::flush;
      width = dhm_images[i].cols;
      height = dhm_images[i].rows;

      sycl::buffer<float, 1> input_dhm(dhm_images[i].ptr<float>(0), range_images[i]);
      input_dhm.set_final_data(nullptr);

      size_t local = std::min(
      height * width,
      device.get_info<cl::sycl::info::device::max_work_group_size>());
      size_t length = height * width;

      do {
      auto f = [length, local, &input_dhm](sycl::handler& h) mutable {
         sycl::nd_range<1> r{sycl::range<1>{std::max(length, local)}, sycl::range<1>{std::min(length, local)}};

         auto aI = input_dhm.template get_access<sycl::access::mode::read_write>(h);
         sycl::accessor<float, 1, sycl::access::mode::read_write, sycl::access::target::local> scratch(sycl::range<1>(local), h);

         h.parallel_for<class sycl_reduction>(
            r, [aI, scratch, local, length](sycl::nd_item<1> id) {
               size_t globalid = id.get_global_id(0);
               size_t localid = id.get_local_id(0);

               if (globalid < length) {
                  scratch[localid] = aI[globalid];
               }
               id.barrier(sycl::access::fence_space::local_space);

               if (globalid < length) {
                  size_t min = (length < local) ? length : local;
                  for (size_t offset = min / 2; offset > 0; offset /= 2) {
                  if (localid < offset) {
                     scratch[localid] = std::max(scratch[localid + offset], scratch[localid]);
                  }
                  id.barrier(sycl::access::fence_space::local_space);
                  }
                  if (localid == 0) {
                  aI[id.get_group(0)] = scratch[localid];
                  }
               }
            });
      };
      queue.submit(f);
      length = length / local;
      } while (length > 1);
   }
   std::cout << "100%\r" << std::endl;
   return 0;
}
```

**Comment by AlexeySachkov** [comment]
Hi @FredrikErikJohansson,

>  What could be the cause of this issue?

According to [OpenCL 1.2 spec](https://www.khronos.org/registry/OpenCL/specs/opencl-1.2.pdf), from the description of `clEnqueueNDRangeKernel`, section 5.8 Executing Kernels:

> CL_OUT_OF_RESOURCES if there is a failure to queue the execution instance of kernel
> on the command-queue because of insufficient resources needed to execute the kernel.
> For example, the explicitly specified local_work_size causes a failure to execute the
> kernel because of insufficient resources such as registers or local memory. Another
> example would be the number of read-only image args used in kernel exceed the
> CL_DEVICE_MAX_READ_IMAGE_ARGS value for device or the number of write-only
> image args used in kernel exceed the CL_DEVICE_MAX_WRITE_IMAGE_ARGS value
> for device or the number of samplers used in kernel exceed
> CL_DEVICE_MAX_SAMPLERS for device.

As you can see, implementation might change the code somehow (due to some optimizations or other transformations) and it might increase size of local/private memory required to execute this kernel

You can try using `clGetKernelWorkGroupInfo` to query actual local/private memory size which is required for kernel execution. SYCL equivalent would be `kernel::get_work_group_info`, but I cannot see a query for local memory in Table 4.86: Kernel work-group information descriptors (probably worth reporting this in KhronosGroup/SYCL-Docs)

**Comment by FredrikErikJohansson** [comment]
Thanks for your fast and thorough response! The problem seems to occur when barriers are used and I'm not sure why. A working solution is to replace `device::max_work_group_size` with `kernel_work_group::work_group_size`. The documentation is quite vague when explaining the difference between these two.

**Comment by AlexeySachkov** [comment]
> `device::max_work_group_size` with `kernel_work_group::work_group_size`

The first one is device-specific theoretical maximum. However, as I said above, because of some transformations or because of usage of local/private memory, the actual limit depends on the kernel content and therefore, the second is much more precise than the first one.

> Thanks for your fast and thorough response! The problem seems to occur when barriers are used and I'm not sure why. 

This is kind of expected. Our CPU device doesn't support barriers in HW and we perform some transformations of kernels to emulate desired behavior: this comes at cost of increased local/private memory consumption. If you are interested in algorithm/approach description you can watch [this](https://www.youtube.com/watch?v=Mm5ATyqm7Rw) video from LLVM-dev where @turinevgeny talks how it is implemented (barrier handling starts at ~7:20)

**Comment by FredrikErikJohansson** [comment]
I see! Once again, thanks for you clear explanation.
