### ISSUE TITLE
[SYCL] Calling kernel within library produces CL_INVALID_KERNEL_NAME 

### ISSUE THREAD

**Issue by pkeir** [intel/llvm#228]
I'm facing a runtime error when I call a SYCL kernel, from within a function, which is in a library.

As a MWE I've renamed `simple-sycl-app.cpp` from GetStartedWithSYCLCompiler.md to `simple-sycl-lib.cpp` and renamed its `main` function to `simple_sycl`. I also added a `main.cpp` which calls `simple_sycl`. The commands to build this are listed below:

```
clang++ -std=c++11 -fsycl -c simple-sycl-lib.cpp -o simple-sycl-lib.o
ar r simple-sycl-lib.a simple-sycl-lib.o
clang++ -std=c++11 -fsycl main.cpp simple-sycl-lib.a -lOpenCL
```

If I run the resulting `a.out` executable, the errors below are issued. I've attached the files involved for convenience: [simple-sycl-lib.zip](https://github.com/intel/llvm/files/3302211/simple-sycl-lib.zip)

```
OpenCL API failed. /home/pkeir/code/ext/intel_sycl/sycl/sycl/source/detail/program_manager/program_manager.cpp:112: OpenCL API returns: -46 (CL_INVALID_KERNEL_NAME)
The result is incorrect for element: 0 , expected: 0 , got: 538976288
The result is incorrect for element: 1 , expected: 1 , got: 1886334752
The result is incorrect for element: 2 , expected: 2 , got: 1852387188
The result is incorrect for element: 3 , expected: 3 , got: 795633012
```

**Comment by romanovvlad** [comment]
@mdtoguchi Could you take a look?

**Comment by bader** [comment]
We need to document how to use new SYCL specific clang options. 
@mdtoguchi, I ready to help with this if needed.

**Comment by mdtoguchi** [comment]
@pkeir,
When using a fat static archive, the archive needs to be passed in with a specific option:  -foffload-static-lib=\<lib\>.  This sets up the needed compilation flow to extract the device information from the archive.  Otherwise, the archive is treated as a normal host archive and is only passed to the final host link.

`clang++ -std=c++11 -fsycl main.cpp -foffload-static-lib=simple-sycl-lib.a -lOpenCL -o new.out`

Using your example and running `new.out`:

`The results are correct!`

**Comment by pkeir** [comment]
Thanks, that works fine here.
