### ISSUE TITLE
[SYCL] const correctness with custom containers

### ISSUE THREAD

**Issue by bd4** [intel/llvm#2538]
I am updating the multi-dimensional array library [gtensor](https://github.com/wdmapp/gtensor) for SYCL 2020 (I previously got it working for SYCL 1.2.1 with USM extension on Intel, I think it was working around beta04).

The change that is proving the most troublesome so far is const-ification of kernel functors and the banning of mutable lambdas. gtensor is written to be const correct, like all containers in the std lib and following best practices. However, this breaks when lambda's can't be mutable, since it's impossible to assign when the captured values (including LHS gtensor array views) are all forced to const. Somehow my current implementation of gtensor array assignment for SYCL is still working (see https://github.com/wdmapp/gtensor/blob/master/include/gtensor/assign.h#L346), when I would expect this to fail because `k_lhs` would be const. The custom kernel launch mechanism, which typically uses mutable lambdas, is not working: https://github.com/wdmapp/gtensor/blob/master/include/gtensor/gtensor.h#L408. For `gt::launch`, the function argument is typically a mutable lambda which does some complex per-element operation and assigns the result to a gtensor view object.

SYCL gets around this with acessors by explicitly forgoing const correctness for write type accessors (See https://github.com/intel/llvm/blob/sycl/sycl/include/CL/sycl/accessor.hpp#L321). Using a similar approach in gtensor is non-trivial - there is an expression class hierarchy, which the view objects are part of. Making just the view type object const-incorrect requires pulling them out of the main class hierarchy and duplicating code, assuming it will work at all. Probably just requires the right meta programming special sauce... but I have to wonder if this is a problem that will affect other library implementers negatively. I understand that there are cases where mutable lambdas are problematic and nonsensical as SYCL kernels, however this seems like a legitimate use case which is impacted by the blanket ban.

@jeffhammond @keryell Interested to hear your input. Also interested to hear how other library implementers are dealing with this - I see the Kokkos port is WIP here: https://github.com/kokkos/kokkos/pull/3231. I'm not very familiar with Kokkos yet - it looks like the view objects, closest thing to gtensor arrays, is not strictly const correct. For gtensor, I don't think abandoning const correctness entirely is a good idea.

**Comment by keryell** [comment]
There were some lengthy discussions in the SYCL committee about this, tracked by the (Khronos-private) issue https://gitlab.khronos.org/sycl/Specification/-/issues/316

At least I can share with you some experiments about work-arounds when some level of mutability is required: https://godbolt.org/z/X6_5pH

I do not know whether it helps you.
Basically you can have a mutable lambda in a kernel, you can add `mutable` to your own classes, you can use `const_cast` at some point (ahem...)...

**Comment by bd4** [comment]
Thanks @keryell the examples are extremely helpful! Good to know this has been explored, even if I'm not sure I like what ended up in the provisional spec.

It looks like at least some of gtensor is 'overly' const correct. In particular it's span implementation is const correct, while the standardized C++20 and gsl::span implementations are not (it is basically a pointer type after all). I am going to try wrapping the user passed mutable lambda in a non-mutable lambda for gtensor custom kernel launch case. For gtensor views, I will explore if I can relax const correctness just for view types, and keep the "owning" types const correct. I will probably need to define a separate branch to the CRTF hierarchy to do this (currently there are two view types, gtensor_view which wraps a span pointing at the underlying gtensor storage, and gview which is basically the slice implementation). I am hoping I can avoid `const_cast` if possible.

Another possibility is to not use USM for the backend - but instead use standard buffers and accessors. This was a suggestion from codeplay. It requires some clever meta programming to avoid changing the gtensor API. The to_kernel routines that convert to a non-owning, copy safe view would need to create accessors (to avoid changing the gtensor API they would have to all be rw, which sort of defeats one of the advantages of the buffer/accessor model...). I am not sure I will have time to explore this but I am curious about it.

I still think there is a bug in current DPCPP that allows my assign kernel to work even with strict const correct view types. Perhaps it's not fully enforcing the 2020 provisional requirements yet.

**Comment by bd4** [comment]
@keryell your workaround for wrapping a mutable lambda in a non-mutable lambda doesn't appear to generalize to the mutable lambda being passed in rather than statically embedded: https://godbolt.org/z/Tznzs5. Or I am doing something wrong here? I think the static case works only because the mutable lambda is defined locally inside the non-mutable lambda. In my case, in need to capture it, which doesn't work because the outer lambda operator() is const and won't allow a non-const operation, namely calling the mutable lambda operator().

This is what the gtensor code looks like:
```
template <>
struct launch<1, space::device>
{
  template <typename F>
  static void run(const gt::shape_type<1>& shape, F&& f)
  {
    sycl::queue& q = gt::backend::sycl::get_queue();
    // wrap a possibly mutable lambda in a non-mutable lambda
    // Fails to compiler with DPCPP beta09
    auto fwrap = [f](int i) { f(i); };
    auto range = sycl::range<1>(shape[0]);
    auto e = q.submit([&](sycl::handler& cgh) {
      using kname = gt::backend::sycl::Launch1<decltype(fwrap)>;
      cgh.parallel_for<kname>(range, [fwrap](sycl::item<1> item) {
        int i = item.get_id(0);
        fwrap(i);
      });
    });
    e.wait();
  }
};
```
The test code looks like this:
```
void device_double_add_1d(gt::gtensor_device<double, 1>& a,
                          gt::gtensor<double, 1>& out)
{
  auto b = gt::empty_like(a);

  auto k_a = a.to_kernel();
  auto k_b = b.to_kernel();

  gt::launch<1>(
    a.shape(), [=](int i) mutable { k_b(i) = k_a(i) + k_a(i); });
  gt::copy(b, out);
}
```
The most obvious workaround here is to have to_kernel return a non const-safe type, then the lambda doesn't need to be mutable. Which is likely need to make the assign kernel work anyway after fixing the bug that is making DPCPP very permissive. I still am not particularly happy with the changes to the gtensor API that this entails. Using a mutable lambda here makes sense, because we are mutating state.

**Comment by bd4** [comment]
Here is a version that compiles, but casting away the const-ness of the passed mutable lambda: https://godbolt.org/z/b9xb17

**Comment by keryell** [comment]
Yes, I cannot see a perfect solution...

**Comment by bd4** [comment]
FWIW, the solution we are landing on is to cast away constness to get things to compile. This is the least invasive change that doesn't affect the CUDA and HIP backend. So far I have this working for the custom kernel launch, using the trick posted above (wrapping in another lambda and casting away const inside). For the assign kernels, I think to be properly spec compliant I will need to cast away const-ness for the LHS, but currently this compiles without that somehow.

**Comment by rolandschulz** [comment]
Using `const_cast` for the lambda seems like a bad solution. That way it will very easy for the user to accidentally trigger UB (if they change any state which isn't a gtensor and is really const.

I think the underlying problem seems to be that gtensor uses const in a weird way for things where it is a view/reference of other data. As you write above "In particular it's span implementation is const correct, while the standardized C++20 and gsl::span implementations are not."

**Comment by bd4** [comment]
@rolandschulz I think gtensor's view objects represent a different design space than std::span. It's worth noting that [xtensor](https://xtensor.readthedocs.io/en/latest/), the non-GPU inspiration for gtensor, also has fully const correct views. Views do have similar copy semantics to span, in that copying a view object does not copy the underlying data (important for copying into GPU compute kernels). However it's much more - it also represents slicing, broadcasting, axis swap, other things you can do in numpy. I.e. it's not 'just' a convenience for passing around array pointers more safely and without copy semantics.

There are cases where you want to pass a view object to a function and have the compiler guarantee that it won't be modified. For std::span, looks like this is done with `span<const T>` rather than `const span<T>`. I think the advantage of something like `const gtensor_view<T, 4>` vs `gtensor_view<const T, 4>` for a 4d view is that the former can be done without constructing a new object when passing to a method that requires const and the original object is not. Or is there a way to do this without a new object? Perhaps a move constructor for 'adding element const-ness' use case can help with this? I don't think I'm the first person to encounter this sort of design trade off, but I'm not finding anything useful in the Cpp core guidelines yet.

**Comment by keryell** [comment]
OK, perhaps I am starting to understand a little bit what you want.
You have a view class A with member functions to access some wrapped data.
You have a `const` view class with member functions to access some data in a `const`-only way.
I guess this is not in a C++ core guidelines because it is very specific to your use case.
For example in the STL the `const`-ness of the wrapper classes does not impact the underlying object (C plain pointer, std::vector, std::shared_ptr...).
A way to do this without invoking the `const`-ness of the view object in a clear way might be to have `A` and `const_A`, with `const_A` inheriting from `A` with an empty-base optimization and just overriding all the non-`const` accessor methods to be `const`.
You can provide a generic `constify()` function to wrap a view into a `const` one.
Otherwise, it seems a pretty fragile programming model in a C/C++ world not aware of your hypothesis.

**Comment by rolandschulz** [comment]
> For std::span, looks like this is done with span<const T> rather than const span<T>.

Correct.

> Or is there a way to do this without a new object?

No. But why would that matter? If something is just a view creating a new object doesn't cause any overhead. And it also doesn't cause extra mental overhead for the user with properly defined conversion operators. E.g. in the case of `std::span` conversion from non-const to const is allowed:
```c++
void f(std::span<const int>);
void t() {
    f(std::span<int>());
}
```

**Comment by keryell** [comment]
I am puzzled by the programming model...

```c++
tensor_view<T, 4> tv { some stuff };
auto a = tv;
const auto b = a;
auto c = b; // What do you get here???
```

**Comment by germasch** [comment]
So since I'm responsible for the semantics in gtensor (though I think it's basically copied from xtensor, but I may actually not have gotten that right, it's not something I had thought about deeply until now), let me try to explain this a bit. And I suspect the answer will be, we should change how constness is handled in gtensor.

The regular owning type `gtensor` behaves just like `std::vector` (except supporting multi-dimensional indices). So in particular, if it's `const gtensor`, you can only read its elements, not modify them. I can't construct a sensible example on how that's a problem with sycl, as I would have to capture the `std::vector` by value, which is exactly what you guys want to prevent, because it doesn't make sense.

This semantics has been carried over into view types, that is a `const gtensor_view<double, N>` also does only allow read but not modification of its elements (even though it doesn't own them in any case). So in some sense, it's just used as an alternative way of having expressing the same as `gtensor_view<const double, N>`. This so far has been fine, and kinda convenient, since one can pass as `const gtensor_view<double, N>&` to a function that doesn't need to modify the values, following the same way as one would pass `const std::vector<double>&` expressing the same intention.

But as I've been thinking about this now, I can't really see a drawback to switching the use of const gtensor_view<double, N>&` to `gtensor_view<const double, N>&`. Actually, there's maybe a little one, that is, one does need a conversion operator to make that work, and the conversion would actually mean temporarily creating a new view object, which is obviously more expensive than just passing a reference. But this shouldn't be a deal breaker, and in particular in those situations where stuff actually gets passed to a kernel, there's already the `.to_kernel()` which replaces references by actual (but still lightweight) objects.

To comment on the last post above:

The semantics are that `a, b, c` all refer to the same (writeable) memory (which needed to be provided when the view was constructed), and `a` and `c` let you modify the data, while `b` doesn't. So yeah, I guess I get your point, the constness isn't safe, though usually it achieves its goals, ie., declaring a function argument `const gtensor_view&` or `const gtensor&` prevents you from directly modifying it, but in the former case it can be easily circumvented by making a new non-const copy of the view.

**Comment by germasch** [comment]
So btw, thanks, even though I haven't thought this all through and in particular tried to see how much hassle it is actually doing this, I think this discussion helped in exposing some hidden issue in gtensor.

**Comment by bd4** [comment]
The `gtensor` object is like a multi-dimension `std::array` - it has fixed number of dimensions, and each dimension is fixed size. Rather than `operator[]` for indexed access, it defines `operator()` so it can accept a variable number of index args depending on the number of dimensions. Just like `std::array` and `std::vector`, the indexing is overloaded on const-ness - the const version returns const_reference, and the non-const version returns reference. xtensor does the same thing, for it's owning objects, and it's view objects. This is "const-correct" in this sense: https://isocpp.org/wiki/faq/const-correctness#return-const-ref-from-const-memfn.

The gtensor objects also have copy semantics, just like std::vector/array. There are cases where we don't want copy semantics, and cases where we want to play games with the indexing without re-arranging the underlying data (slicing, axis swapping, broadcasting). View objects do both things. The question is, how should view objects behave with respect to the const-correctness of their indexed access methods? Should they also return a const reference if called on a const view object, like gtensor, or should they relax this constraint and return a non-const reference? Is the underlying data part of the view object state, or is it just a pointer like span? Or should constness live in the element type like for std::span?

Where lambda's come in is defining complex per GPU thread operations, that can't be expressed in gtensors array operator syntax. This is a dumb example because it can be expressed in array syntax, but BLAS axpy operation could be implemented like this:
```
  constexpr int n = 1024*1024*1024;
  double a = 3.141592653589793;
  gt::gtensor<double, 1, gt::space::device> d_x(gt::shape(n));
  gt::gtensor<double, 1, gt::space::device> d_y = gt::empty_like(d_x);
  gt::gtensor<double, 1, gt::space::device> d_axpy;
  d_axpy = gt::empty_like(d_x);

  // initialize arrays

  // convert to views that can be based to kernel with pointer-like semantics
  auto k_x = d_x.to_kernel();
  auto k_y = d_y.to_kernel();
  auto k_axpy = d_axpy.to_kernel();

  gt::launch<1>(
    d_x.shape(), GT_LAMBDA(int i) mutable { k_axpy(i) = a * k_x(i) + k_y(i); });
```

If the view objects have a const-overload for operator() that returns a const reference, the lambda must be mutable. And so this code breaks works in SYCL 1.2.1 and breaks in SYCL 2020.

@germasch I wrote this before seeing your post... I'm pretty sure gtensor semantics do correctly match xtensor. Or at least their view classes definitely have the const overload, not sure if they also have conversion operators to allow simple `view<const T> = view<T>`.

Representing the "const-ness" in the element type seems like it's worth considering, although my modern C++ is weak so I need to write it to understand all the implications. I still haven't seen anything that makes me believe that what xtensor and gtensor currently do is bad practice. It just happens to not play well with SYCL 2020 provisional spec and how gtensor needs to pass views to kernels.

**Comment by bd4** [comment]
I've been pretty loose with the "const correctness" terminology and I think it's causing confusion in the discussion. It's clearer to talk about what is a container or container view's state - does it include the underlying data or not? If the state includes the underlying data, indexed accessors on a const instance should be const ref, to preserve "const correctness" (clearly true for owning container objects like std::vector, gtensor, xtensor, etc). For views, the underlying data is not part of the state as far as copying goes, so it could be argued that it should not be considered part of the state when deciding on whether to return a const ref or a non const ref. xtensor views are a hybrid - copying an xview does not copy the underlying data, but the indexing operator returns a const ref anyway. And gtensor has followed this design choice so far.

**Comment by rolandschulz** [comment]
Using const like this isn't correct for views. As soon as the view is being copied it isn't const anymore: https://godbolt.org/z/7rq9sT

**Comment by bd4** [comment]
I see your point @rolandschulz . Unfortunately, the design of xtensor/gtensor involves a very carefully coupled set of CRTP to define compile time resolved lazy evaluation expressions. Disentangling them in a way so that views and containers have different const-ness semantics is very much non-trivial. I'm beginning to suspect this is why xtensor did it this way - not because const views are meaningfully "safer", but because they are waaay easier to implement as part of expressions...

It turns out this was easy for the gtensor_view object, which is just a wrapper around span that does multi-dimensional indexing. The gview class that handles offset / slicing / etc is much more difficult.

**Comment by bd4** [comment]
I'm going to go ahead an close this issue. It's specific enough to gtensor that I don't think I'm going to convince anyone to change the SYCL spec. If anyone is curious the eventual resolution will exist somewhere in a PR at https://github.com/wdmapp/gtensor

**Comment by keryell** [comment]
It would be interesting to get some people from https://github.com/xtensor-stack/xtensor to give feedback on this concept of `const`-ness perfection @SylvainCorlay

**Comment by bd4** [comment]
I created an issue on the gtensor tracker: https://github.com/wdmapp/gtensor/issues/39
