### ISSUE TITLE
[SYCL][CUDA] issues with NVPROF

### ISSUE THREAD

**Issue by jeffhammond** [intel/llvm#2692]
DPC++ appears to not support kernel replay that is required for NVPROF to count flops on NVIDIA devices.

This is not surprising and I do not expect a fix in the near future.  I am logging this issue for posterity.

NVPROF works just fine with the default settings and with the metric shown below.  It is only with the flop counting that triggers kernel replay that causes NVPROF to fail.

# Works
```
$ nvprof --metrics gld_throughput  ./qs
...
Using SYCL device
...
==64763== Profiling application: ./qs
==64763== Profiling result:
==64763== Metric result:
Invocations                               Metric Name                        Metric Description         Min         Max         Avg
Device "GeForce GTX 1080 (0)"
    Kernel: _ZTSZZ13cycleTrackingP10MonteCarloENKUlRN2cl4sycl7handlerEE276_52clES4_EUlNS2_4itemILi1ELb1EEEE277_66
        195                            gld_throughput                    Global Load Throughput  10.906MB/s  3.0486GB/s  1.4841GB/s
```

# Broken
```
$ nvprof --metrics gld_throughput,flops_dp  ./qs
...
Using SYCL device
==62880== Some kernel(s) will be replayed on device 0 in order to collect all events/metrics.
PI CUDA ERROR:
 Value:           999
 Name:            CUDA_ERROR_UNKNOWN
 Description:     unknown error
 Function:        cuda_piEnqueueKernelLaunch
 Source Location: /media/disk2/jrhammon/llvm/sycl/plugins/cuda/pi_cuda.cpp:2376
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
==62880== Profiling application: ./qs
==62880== Profiling result:
No events/metrics were profiled.
==62880== Warning: Some profiling data are not recorded.
======== Error: Application received signal 134
```

**Comment by GeorgeWeb** [comment]
Hi @jeffhammond 

I appreciate this was reported a very long time ago, so apologies for the belated response.

`nvprof` isn't well supported going forward with architectures and Nvidia has deprecated its use since `sm_70` by requesting users to transition to using **Nsight Compute** for GPU profiling and **Nsight Systems** for GPU tracing and CPU sampling.
```
nvprof --metrics gld_throughput,flops_dp ./out
======== Warning: Skipping profiling on device 0 since profiling is not supported on devices with compute capability 7.5 and higher.
                  Use NVIDIA Nsight Compute (`ncu`) for GPU profiling and NVIDIA Nsight Systems (`nsys`) for GPU tracing and CPU sampling.
                  Refer https://developer.nvidia.com/tools-overview for more details.
```

**Nsight Compute** is supported from `sm_70` onwards but those are newer GPUs than that in the reported issue (`GeForce GTX 1080`). For that reason, if using an SM 7.0 capable device, I'd recommend switching to **Nsight Compute** using the [Nvprof Transition Guide](https://docs.nvidia.com/nsight-compute/NsightComputeCli/index.html#nvprof-guide). The same metrics can be collected by using the equivalent metrics for `ncu` which can be found in the [Metric Comparison](https://docs.nvidia.com/nsight-compute/NsightComputeCli/index.html#nvprof-metric-comparison) section of the transition in **Table 10. Metrics Mapping Table from CUPTI to PerfWorks**. 

The `nvprof` metric `flops_dp` (or `flop_count_dp`) equates to the PerfWorks Metric or Formula (>= SM 7.0):
```
smsp__sass_thread_inst_executed_op_dadd_pred_on.sum
+ smsp__sass_thread_inst_executed_op_dmul_pred_on.sum
+ smsp__sass_thread_inst_executed_op_dfma_pred_on.sum * 2
```
and `gld_throughput` equates to `l1tex__t_bytes_pipe_lsu_mem_global_op_ld.sum.per_second`.
With Nsight Compute installed, you can gather this data from the counters as follows:
```
ncu --metrics=l1tex__t_bytes_pipe_lsu_mem_global_op_ld.sum.per_second,smsp__sass_thread_inst_executed_op_dadd_pred_on.sum,smsp__sass_thread_inst_executed_op_dmul_pred_on.sum,smsp__sass_thread_inst_executed_op_dfma_pred_on.sum ./out
```
---

Alternatively to requiring an SM 7.0+ GPU, older versions of the cuda toolkit (pre 2020 release) may still have `ncu` support for SM 6.x, but I cannot guarantee now which version exactly dropped it unfortunately.

So, we may look into this for older GPUs and we do have this bug tracked, but it is currently still of low priority.

I hope that for now this can be at least somewhat helpful to proceed.
Let me know if you have any further enquiry related to this.
