### ISSUE TITLE
[Questions] multiple reduction objects using SYCL buffers

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#2791]
```
template <typename KernelName, typename KernelType, int dimensions, typename... Rest>
void parallel_for(range<dimensions>numWorkItems, Rest&&... rest);

The rest parameter pack consists of 0 or more reduction objects followed by the kernel functor.
```

It is not clear how we can pack multiple reduction objects when these objects are not stored in an array. Could you please provide an example ? 

```
for (int i = 0; i < N; i++) {
   ... 
   a += r + dx * dx;  // reduction over a
   b += k + dx * dx; // reduction over b
}
```

```
queue.submit([&](handler& cgh)
{
    auto a = accessor<int,0,access::mode::write, access::target::global_buffer>(a_buf, cgh);
    auto b = accessor<int,0,access::mode::write, access::target::global_buffer>(b_buf, cgh);
    cgh.parallel_for(nd_range<1>{N, M}, reduction(a, 0, plus<int>()), reduction(b, 0, plus<int>()),
                                                              [=](nd_item<1> it, auto& a, auto &b)
    {
        int i = it.get_global_id(0);
        ... 
        a += r + dx*dx;
        b += k + dx*dx;
    });
});
```
Thanks for your instruction

**Comment by Pennycook** [comment]
Hi @zjin-lcf.  I'm not sure I understand your question -- the code snippet you've posted looks right to me.

The `parallel_for` function is variadic and so accepts any number of arguments.  It accomplishes this through the use of a template [parameter pack](https://en.cppreference.com/w/cpp/language/parameter_pack).  This is what the `...` signifies in `typename... Rest` and `Rest&&... rest`.  The fact that this function uses a parameter pack isn't something that a developer of DPC++ kernels should have to pay any attention to -- things are specified this way for implementers.

In your example, the parameter pack consists of two reduction objects followed by a kernel functor (the lambda).  You don't need to wrap your reduction objects in some sort of container for things to work.

If you're getting a compiler error when you try to compile code like the above, that's because supporting multiple variables in a reduction [isn't supported yet](https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions).  This is something that we are actively working on.

**Comment by zjin-lcf** [comment]
I am not a c++ guy, so I posted an example (correct or incorrect) to make others better understand my question. 
Could you explain "You don't need to wrap your reduction objects in some sort of container for things to work." ?

**Comment by Pennycook** [comment]
> I am not a c++ guy, so I posted an example (correct or incorrect) to make others better understand my question.
> Could you explain "You don't need to wrap your reduction objects in some sort of container for things to work." ?

Sure.  Sorry for the confusion.  You said "It is not clear how we can pack multiple reduction objects when these objects are not stored in an array." -- I was trying to point out that the developer doesn't have to pack multiple reduction objects into anything at all.  The concept of a "pack" comes from C++, and you don't have to do anything special to use them.

Your code example is correct.  You can pass as many reduction objects as you want to into `parallel_for`.

Building on your example, here's how you'd increase the number of reduction objects from 2 to 3:
```
cgh.parallel_for(nd_range<1>{N, M},
                 reduction(a, 0, plus<int>()),
                 reduction(b, 0, plus<int>()),
                 reduction(c, 0, plus<int>()),
                 [=](nd_item<1> it, auto &a, auto &b, auto &c) { /* kernel body goes here */ });
```

**Comment by zjin-lcf** [comment]
Thanks for your answers!

**Comment by zjin-lcf** [comment]
Thank you for your update when the feature is available.
