### ISSUE TITLE
mutable device lambda

### ISSUE THREAD

**Issue by paboyle** [intel/llvm#2843]
Gold on devcloud bans [=] mutable device lambdas, and 2020 SYCL draft spec.

This prevents use of any struct or class as a captured parameter with a call to a method not declared as const.

Lambdas are useful to avoid explicit and tedious parameter listing on a case by case basis.

Capturing any struct or compound object with a non-const method (whether modifying or not) or modifying action upon it inside the device kernel is now banned & illegal.

The behaviour is clearly supportable, since you can always in an explicit coded case make a non-const copy of the copied by value const object. However, since the lambda is the general case convenient to use in Grid, Raja or Kokkos, it prevents doing this generally. My code Grid uses a mutable capture in HIP, SyCL and CUDA, and this no breaks in the Gold version.

Further, perfectly reasonable code could capture a device iterator, and increment it in the kernel over some limited range.
(for example). It's not unreasonable to make modifying calls on a copy you are given.

This seems to me to be a dictation of C++ coding policy that goes way beyond hardware constraints and decreases the attractiveness of the language & compiler. Starting to look at OpenMP instead.

**Comment by AlexeySachkov** [comment]
Tagging @Pennycook, @mkinsner and @cperkinsintel to comment here

**Comment by cperkinsintel** [comment]
@paboyle , you seem to want to use the `mutable` keyword as a way to sneak in capture-by-reference, because that makes it simpler to code, correct? You just want the ability to easily capture up some struct but don't actually intend to modify it in any meaningful way, no?

The problem is that in C++ mutable lambdas should both allow and support mutation. Even in pre-gold versions you'll find that while mutable lambda code that captures variables compiles (nice!) it doesn't actually work ( !! ) . If you modify that variable on a device, those changes will not be propagated back to the calling context.  Meaning the "mutability" aspect of "mutable" is missing.     
I am not on the SYCL committee, but I believe that is the key reason that mutable lambdas have been proscribed. 

Does that answer your question? Did I overlook anything?

**Comment by paboyle** [comment]
No - capture by reference would modify the original copy on the host surely, and would be a bug.

I want to capture structs or classes by value, but be able to modify or call non-const qualified methods.
So I do mean:
[=] mutable.

For example I have my _own_ containers and then partner "view" objects which have non-const operator [] methods but the container object contains only a pointer as a data member that points to either USM or device memory and is safe to copy by value to device, but operate with non-const.

This code is written to be portable across CUDA, HIP and SYCL, and compiled fine up to Beta10 but breaks on Gold.

**Comment by paboyle** [comment]
As a software design, 
the container contains no operator [], and 
the lean "View" class contains operator [] for both Lvalue (non-const) and Rvalue const.

```
  accelerator_inline const vobj & operator[](size_t i) const { return this->_odata[i]; };
  accelerator_inline vobj       & operator[](size_t i)       { return this->_odata[i]; };
```

They have a common base containing only the device/USM pointer and the Container has a View() method to obtain a view for passing to an offloaded parallel_for, safely captured by value.

Mutable is required to call the operator[]  lvalue accessor.

Note to do this cross platform, I have my own home grown caching options with a single implementation that runs on top of HIP, SYCL or CUDA. Using Buffers for this is not an option as a result, but the rich functionality that is needed to implement Buffers is needed within user level code to do this.

**Comment by paboyle** [comment]
Schematically (this is no longer cut and paste from my code, but a sketch)...
```
class view {
private:
  device_ptr data;
public:
  accelerator_inline const vobj & operator[](size_t i) const { return this->data[i]; };
  accelerator_inline vobj       & operator[](size_t i)       { return this->data[i]; };
}
```

This can refer entirely to memory that is on the device. 
operator [] can be called on the view, and modify data on the device.
The contents of the view are NOT modified.
The memory pointed to by the view lives and the device and its modified.

**mutable** is required to call the non-const method.

object is safe to copy from host to device. It only contains a pointer to device accessible memory.

**Comment by Pennycook** [comment]
One of the big problems here is that different people have different expectations of how a C++ callable is converted into a kernel in the first place (even without `mutable`), and adding `mutable` makes that even more complicated.

Without `mutable`, everything captured by the lambda is `const`.  That makes it legal for implementations to do things like cache kernel arguments in some special memory, rather than create a separate copy for every work-item.  It's possible that some implementations and hardware are relying on this property of lambda capture for correctness.

Note that from a SYCL language perspective the lambda that we're talking about _is_ the kernel -- if the lambda is `mutable`, what does it mean to modify the kernel's state?  There are several possibilities:
- The lambda exists on the host and device, so modifications to its state should be visible on the host.
- The lambda exists independently of being invoked as a kernel, so modifications to its state should be visible across multiple calls to `parallel_for`.
- A copy of the lambda is created only once for the device, so modifications to its state should be visible across multiple work-items executing the same `parallel_for`.
- A copy of the lambda is created for each work-item, so modifications to its state are private and visible only within a work-item.

Each of these interpretations of `mutable` would require a different implementation of SYCL, because they require the lambda (and its members) to be stored in a specific kind of memory and copied between the host and device in a specific way. 
 Disallowing `mutable` lambdas is a simple way to ensure that all implementations have the same behavior across all hardware.

Could you share a small example code using your `view` class?  It might be that there's a simple workaround; it might be that we need to come up with some new way to enable your use-case.

**Comment by paboyle** [comment]
Those with incorrect expectations should read the manual.
[=] mutable is well documented as allowing modification within the lambda and no effects outside the lambda.

**Comment by paboyle** [comment]
I've parsed your question more.

I wish the lambda to in effect be a unique mutable copy per work item. 

Note, I don't in fact modify the lambda, but only data pointed to by the lambda.

I simply call functions that are not declared const, and necessarily so, to make a legal lvalue index operation.
The non-const / const operator[] idioms are constraints of the language.

That said, I would view it as your

A copy of the lambda is created for each work-item, so 
modifications to its state are private and visible only within a work-item.

That same way as if I wrote 
```
for(i) {
   auto lambda  [=] (cl::sycl::nd_item<3> item) mutable {  .... BODY ....  };
   lambda();
}
```

The last case you list is the only mutable that makes sense for reasons of explicit concurrency of the parallel for.

Parallel for could be documented as only ever copy by value, and even the lambda itself is copied into the loop iteration.


I see no reason or confusion over mutability, but everything copied to device is copied by value.

**Comment by Pennycook** [comment]
> [=] mutable is well documented as allowing modification within the lambda and no effects outside the lambda.

I don't think it's that simple.  I agree that the meaning of a `mutable` lambda is clear -- what's unclear is when an implementation is expected to create copies of that lambda.  Here's a simple example (also https://godbolt.org/z/sjq86z):

```c++
#include <iostream>

template <typename Functor>
void parallel_for_implementation_1(int N, Functor f)
{
    for (int i = 0; i < N; ++i) {
        f(i);
    }
}

template <typename Functor>
void parallel_for_implementation_2(int N, Functor f)
{
    for (int i = 0; i < N; ++i) {
        Functor fcopy = f;
        fcopy(i);
    }
}

int main()
{
    int x = 0;
    parallel_for_implementation_1(5, [=](int i) mutable {
        std::cout << "implementation 1: i = " << i << ", x = " << x++ << std::endl;
    });
    parallel_for_implementation_2(5, [=](int i) mutable {
        std::cout << "implementation 2: i = " << i << ", x = " << x++ << std::endl;
    });
}
```

Which prints:
```c++
implementation 1: i = 0, x = 0
implementation 1: i = 1, x = 1
implementation 1: i = 2, x = 2
implementation 1: i = 3, x = 3
implementation 1: i = 4, x = 4
implementation 2: i = 0, x = 0
implementation 2: i = 1, x = 0
implementation 2: i = 2, x = 0
implementation 2: i = 3, x = 0
implementation 2: i = 4, x = 0
```

The semantics that you're expecting force each work-item to have its own copy of the lambda.

Note that the way I've written things (`Functor f`) implicitly creates a copy of the lambda when invoking the "device" code.  If I'd written `Functor&& f` instead, the same lambda could be invoked in the "host" and "device" code and would share a state.

I want to be clear, here -- I'm not arguing that your expectations of how this should work are unreasonable.  I'm just trying to show that it's not enough to say that everybody should have the same expectation just because the lambda is declared `mutable`.  Ensuring that every implementation produced the same results for a `mutable` lambda requires consensus on what those results should be, then pinning down exactly what the specification needs to say to ensure that all implementations produce those results.

**Comment by paboyle** [comment]
Parallel for implementation 1 is an intrinsically sequential / ordered definition and not parallel.
Suggest to define parallel_for to mean take a copy of the thing to device thread and execute it in parallel with no
non-sequential difficulty.

**Comment by Pennycook** [comment]
Thanks, Peter.  This is useful feedback.

**Comment by paboyle** [comment]
https://godbolt.org/z/o8zsxd

I'd argue tweaking your case to make the functor be allocated outside the loop, and looking at how execution
of the same functor inline and in a parallel loop executor displays more uniformity. 

You take a copy of it to the device, and the host functor doesn't change state. 

That is consistent with the genuine parallel execution implementation 2.

But different from the implementation 1, where the original state functor is not updated on the host stack,
but magically updates between loop iterations.

As you're taking a copy, always take a copy.

**Comment by paboyle** [comment]
```
#include <iostream>

template <typename Functor>
void parallel_for_implementation_1(int N, Functor f)
{
    for (int i = 0; i < N; ++i) {
        f(i);
    }
}

template <typename Functor>
void parallel_for_implementation_2(int N, Functor f)
{
    for (int i = 0; i < N; ++i) {
        Functor fcopy = f;
        fcopy(i);
    }
}

int main()
{
    int x = 0;
    auto functor = [=](int i) mutable {
        std::cout << " i= " << i << ", x = " << x++ << std::endl;
    };
    functor(0);
    parallel_for_implementation_1(5, functor);
    parallel_for_implementation_2(5, functor);
    functor(0);
}
```
producing:
```
i= 0, x = 0
 i= 0, x = 1
 i= 1, x = 2
 i= 2, x = 3
 i= 3, x = 4
 i= 4, x = 5
 i= 0, x = 1
 i= 1, x = 1
 i= 2, x = 1
 i= 3, x = 1
 i= 4, x = 1
 i= 0, x = 1
```

**Comment by paboyle** [comment]
Perhaps better explanation of that last point:
```
    parallel_for_implementation_2(2, functor);
```
is the same as:
```
    for(int i=0;i<5;i++) {
      parallel_for_implementation_2(1, functor);
    }
```
and automatically order invariant. You could to the iterations in reverse order etc....
It's just a clearly parallel scheme as you would expect of dpcpp.

I think this makes the definition for [=] mutable a unique sensible choice.

**Comment by keryell** [comment]
We had a lengthy discussion on this inside the SYCL committee...
While the discussions are not public I can share some code sample I wrote to argument the discussion:
https://godbolt.org/z/X6_5pH
where I show 2 work-arounds to have some mutability.
I hope it helps.

**Comment by Pennycook** [comment]
As @keryell said, this was discussed extensively within Khronos before SYCL 2020 settled on disallowing `mutable` lambdas.  The "what changed" appendix ([Appendix D](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:what-changed-between)) explains:

> Kernel invocation functions, such as `parallel_for`, now take kernel functions by `const` reference. Kernel functions must now have a `const`-qualified `operator()`, and are allowed to be copied zero or more times by an implementation. These clarifications allow implementations to have flexibility for specific devices, and define what users should expect with kernel functors. Specifically, kernel functors can not be marked as `mutable`, and sharing of data between work-items should not be attempted through state stored within a kernel functor.

If it is desirable for each work-item to have its own private copy of a variable, the simplest work-around is to declare a new variable within the kernel.  This is explicit and will always give the same behavior across implementations: the kernel arguments (whether captured by a lambda or stored in a function object) will be constant throughout a kernel's execution, and copies of those arguments declared within the kernel will be stored in the private address space.

The other common case where `mutable` appears desirable is when capturing an object that provides an interface to some other data.  Having a `const`-qualified `operator()` may require some changes to user code, but these changes are consistent with C++ best practices.  Classes that provide a _view_ of some underlying data can still be implemented in a way that is compatible with `const`-correctness.
