### ISSUE TITLE
Rename sycl::INTEL::gpu to sycl::intel::gpu

### ISSUE THREAD

**Issue by sapoluri** [intel/llvm#2903]
For the latest official release, the namespace is declared as sycl::INTEL::gpu. While all previous releases as well as some documentation refers to it as sycl::intel::gpu.

Please use one or the other.

**Comment by AlexeySachkov** [comment]
Hi @sapoluri, thanks for the report

If I understand correctly, `intel` -> `INTEL` change was done in order to align with extensions mechanism from upcoming SYCL 2020, in particular see: https://github.com/intel/llvm/pull/2231#issuecomment-668096120.

Looking at #2246 I don't see documentation updated, tagging @jbrodman and @Pennycook for awareness

**Comment by alexbatashev** [comment]
The extension naming scheme was updated to conform to latest SYCL 2020 specification. Please, re-open if you disagree.
