### ISSUE TITLE
[SYCL] Does sycl support CUDA Multi-Device System?

### ISSUE THREAD

**Issue by malixian** [intel/llvm#2969]
For example, I have two same GPUs . How can I specify different operators to execute on different GPUs in a sycl program? Like cudaSetDevice(int device_id) function.

**Comment by keryell** [comment]
The SYCL standard handles any number of accelerators through the concept of `sycl::device` and you can execute kernels on them through different `sycl::queue` you have to create.
You can use the concept of device selector to select the device you want or directly look at all the device list from `sycl::device::get_devices()`
Look for example at https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf for these classes or at some SYCL tutorials or book on https://sycl.tech/
The SYCL committee did not follow the path of old APIs likes `cudaSetDevice()` because this is not thread-safe to have so much hidden state handled by the current C++ `std::thread`.
Instead, we have a clearer and safer explicit API.

**Comment by malixian** [comment]
thx for @keryell, this question has been resolved.
