### ISSUE TITLE
Upstream __builtin_unique_stable_name implementation to llvm-project.

### ISSUE THREAD

**Issue by bader** [intel/llvm#3063]
`__builtin_unique_stable_name` implementation was reverted in llorg - https://reviews.llvm.org/rGcec49a583693752b3984e49f9c193de07c2a7698, but it's still used in DPC++ headers and required for successful parsing with llorg's version of clang.

**Comment by illuhad** [comment]
Is there anything we can do to accelerate the process of getting this back in upstream clang?

This is a key bit of functionality for future developments in hipSYCL, and is in fact already used in some hipSYCL PRs because it was part of the official clang 11 release. We will not be able to support clang 12 without it. (I'm quite unhappy that features vanish silently from upstream clang even though they were already part of an official release..)

**Comment by bader** [comment]
@erichkeane, do you have any suggestions?

**Comment by erichkeane** [comment]
We've got a developer working with a pair of community members to design an appropriate replacement.  @schittir can give you an update on that progress.  If @illuhad would like to help, she can also help with that discussion.

**Comment by illuhad** [comment]
@erichkeane Thanks for the update! I would be interested in how that replacement would like, at least the interface of it since we require that functionality.

PS: I'm a guy ;)

**Comment by erichkeane** [comment]
> 
> 
> @erichkeane Thanks for the update! I would be interested in how that replacement would like, at least the interface of it since we require that functionality.

Interface wise I think we want it to look the same. The biggest concern is how to make the string/mangling both demangleable AND unique/stable.  The initial implementation was intended for a proof-of-concept and was never updated so it uses source-location information to create the uniqueness.  We're likely going to instead replace that with something similar to the integral-value discriminator that lambdas get on a per-decl-context basis, except only number the lambdas important to the kernel.  Again, @schittir can fill you in.
 
> PS: I'm a guy ;)

@schittir however is not, which is who the 'she' referred to.

**Comment by illuhad** [comment]
> Interface wise I think we want it to look the same. The biggest concern is how to make the string/mangling both demangleable AND unique/stable. The initial implementation was intended for a proof-of-concept and was never updated so it uses source-location information to create the uniqueness. We're likely going to instead replace that with something similar to the integral-value discriminator that lambdas get on a per-decl-context basis, except only number the lambdas important to the kernel. Again, @schittir can fill you in.

That's great news. So, I will be able to develop against the current interface and it will continue to work. I assume the concern about mangling is because of debugging/tooling?

> @schittir however is not, which is who the 'she' referred to

Ah, sorry, I misinterpreted that sentence.

**Comment by erichkeane** [comment]
> 
> 
> > Interface wise I think we want it to look the same. The biggest concern is how to make the string/mangling both demangleable AND unique/stable. The initial implementation was intended for a proof-of-concept and was never updated so it uses source-location information to create the uniqueness. We're likely going to instead replace that with something similar to the integral-value discriminator that lambdas get on a per-decl-context basis, except only number the lambdas important to the kernel. Again, @schittir can fill you in.
> 
> That's great news. So, I will be able to develop against the current interface and it will continue to work. I assume the concern about demangling is because of debugging/tooling?

That is the concern with wanting it to be demangled, yes. Crashes tend to print this name, so it is a pretty poor user interface when they don't know the name of what kernel crahsed.  However, it was reverted because of the hacky-way in which we initially derived uniqueness.

**Comment by schittir** [comment]
Hi @illuhad, 

I second Erich's comment about the interface remaining the same. That goal is to leave it unchanged.  
  
The following are the main ideas of the new design that emerged from discussion with community members. 
1.  Add "kernelness" to lambda signature to distinguish kernel-involved lambda from others: 
     Discussion here: https://reviews.llvm.org/D76620 
2.  Ensure correct/instantiation-independent order for kernel-involved lambdas by using a separate local numbering based on their order in the declcontext; Details below: 
      a. Go through Sema and detect when a symbol relies on a type with unstable numbering. 
      b. Record the above types using a DenseMap</*local*/DeclContext*, > DenseSet<TagDecl*>>, and add an entry for every
           local type that’s part of the identity of a kernel function. 
      c. Based on the local context, keep an ordinary local number for kernel-involved types 
      d. Now apply a special mangling to these kernel-involved local numbers. 
      e. Update kernel name with the new value in SemaSYCL. 

The requirement is also to make it demanglable also, like Erich pointed out, but this aspect is not fleshed out yet. 
The implementation work is in progress. Please feel free to suggest ideas/discuss anything.  

Thank you. 
Sindhu

**Comment by illuhad** [comment]
Thanks for your insights, @schittir.

I quite liked the previous approach because it also solved the pathological macro `#ifdef` that is mentioned at the end of the discussion you have linked. If I understand correctly, this is now solved by numbering kernel-involved lambdas separately?

I'm a bit concerned about the "kernelness". How is it determined if a lambda is part of a kernel, exactly?
I'm asking because I don't use the SYCL frontend, and the hipSYCL host pass doesn't have any additional compiler support available apart from regular clang C++. This is fine with the current approach based on line/column numbers, as it returns the same name no matter if it is in a heterogeneous compilation mode or not. If I understood correctly, in the new approach I am not guaranteed that `__builtin_unique_stable_name()` returns the same in the host pass as in the device pass unless I can also somehow tell it in the host pass that the lambda is going to be used as a kernel?

**Comment by schittir** [comment]
> Thanks for your insights, @schittir.
> 
> I quite liked the previous approach because it also solved the pathological macro `#ifdef` that is mentioned at the end of the discussion you have linked. If I understand correctly, this is now solved by numbering kernel-involved lambdas separately?
Correct. The local context based numbering of kernel-involved lambdas addresses this issue. 

> I'm a bit concerned about the "kernelness". How is it determined if a lambda is part of a kernel, exactly? 
"Kernelness" is set in Sema::CheckSYCLKernelCall when a kernel object (a CXXRecordDecl) is a lambda. 

> I'm asking because I don't use the SYCL frontend, and the hipSYCL host pass doesn't have any additional compiler support available apart from regular clang C++. This is fine with the current approach based on line/column numbers, as it returns the same name no matter if it is in a heterogeneous compilation mode or not. If I understood correctly, in the new approach I am not guaranteed that `__builtin_unique_stable_name()` returns the same in the host pass as in the device pass unless I can also somehow tell it in the host pass that the lambda is going to be used as a kernel?
Yes, in the new approach, the value returned by `__builtin_unique_stable_name()` might be different between passes. 
Good point. I will check again.

**Comment by illuhad** [comment]
> Yes, in the new approach, the value returned by __builtin_unique_stable_name() might be different between passes.
Good point. I will check again.

Thanks for checking. In general, I believe there is great value in keeping this feature independent from the SYCL frontend. This is because an independent `__builtin_unique_stable_name()` allows building frameworks that aggregate compiled kernels from device passes from different clang-supported heterogeneous models (SYCL/CUDA/HIP/...) in a single binary. This requires having a pure C++ host pass, and is exactly what hipSYCL does to target CUDA and HIP devices simultaneously with clang.

Would it maybe work if an additional generic attribute were introduced, say, `requires_stable_arguments`, that when attached to a function attaches the "kernelness" to all arguments?

This would 
* Solve my problem with the pure C++ host pass, because I could just instantiate a dummy function during the host pass to attach the kernelness information:
 ```c++ 
template<class LambdaT>
 __attribute__((requires_stable_arguments)) void dummy_kernel(LambdaT f){}
```

* also be usable by DPC++/clang SYCL without additional changes to SemaSYCL:
```c++
template <typename KernelName, typename ElementType, typename KernelType>
 __attribute__((sycl_kernel, requires_stable_arguments)) 
void kernel_parallel_for(KernelType KernelFunc) {...}
```
* It might even be useful for CUDA/HIP because we might able to `#define __global__ __attribute((global, requires_stable_arguments))`

**Comment by bader** [comment]
> In general, I believe there is great value in keeping this feature independent from the SYCL frontend.

I'd like to add that this was also requested in the comment for review @schittir mentioned earlier - https://reviews.llvm.org/D76620#2327617.

**Comment by keryell** [comment]
> However, it was reverted because of the hacky-way in which we initially derived uniqueness.

If I remember correctly it was not reverted because it was intrinsicly bad but because it was introduced as a generic Clang builtin without strong RFC and some important Clang contributors did not want this to be cast in stone forever. I have the feeling it could have been added and accepted as a SYCL-specific builtin in at the first place as an experimental workbench to play with and tune it more freely.

**Comment by erichkeane** [comment]
> 
> 
> > However, it was reverted because of the hacky-way in which we initially derived uniqueness.
> 
> If I remember correctly it was not reverted because it was intrinsicly bad but because it was introduced as a generic Clang builtin without strong RFC and some important Clang contributors did not want this to be cast in stone forever. I have the feeling it could have been added and accepted as a SYCL-specific builtin in at the first place as an experimental workbench to play with and tune it more freely.

That does not reflect my conversation with John McCall about it.  He/Richard are open to the feature if we can implement it in a more sane way, which we've been working closely with John to architect an acceptable solution.

**Comment by bader** [comment]
BTW, @erichkeane, can we close this?

**Comment by erichkeane** [comment]
Re-implementation (with a different name and slightly different syntax) here: https://github.com/llvm/llvm-project/commit/eba69b59d1a30dead07da2c279c8ecfd2b62ba9f
