### ISSUE TITLE
queue::wait doesn't wait

### ISSUE THREAD

**Issue by pkeir** [intel/llvm#3101]
I believe the call to `queue::wait` in the program below should perform a blocking wait for the completion of all enqueued tasks in the queue. Instead, I get a segmentation fault. If I uncomment the pair of braces, the buffer is destroyed, and the code executes correctly. I compile with `clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice qw.cpp` using CUDA 10.1 on Ubuntu 20.10 using a build (via `configure.py --cuda` etc.) from commit 5500262254c3b712e999195972d19fcb6dfde9ff. Is the program well-formed?

```
#include <CL/sycl.hpp>
class Foo;

int main(int argc, char *argv[])
{
  using namespace cl::sycl;
  unsigned sz{1024};
  range<1> r{sz};
  unsigned *p = new unsigned[sz]{}; // zeroed

  queue q;

//  {  // buffer zone

    buffer<unsigned,1> buf{p, sz};

    q.submit([&](handler& cgh)
    {
      auto acc = buf.get_access<access::mode::write>(cgh);
      cgh.parallel_for<Foo>(r, [=](id<1> i) {
        acc[i] = 9;
      });
    });

//  }  // buffer destroyed

  q.wait();

  bool b = p[0]==9;
  delete [] p;

  return b ? 0 : -1;
}
```

**Comment by romanovvlad** [comment]
I think it crashes because the buffer `buf` tries to make copy back to the pointer, passed during construction `p`, in its desctructor, but destructor due to standard C++ rules runs at the end of the main function after `p` has been `delete`d.
The program is ill-formed, it is illegal to access pointer passed to the buffer c'tor in this way until the buffer is destroyed.
Lines `bool b = p[0]==9;` and `delete [] p;` should be placed after buffer is destroyed.

**Comment by pkeir** [comment]
Thanks. Yes, I see now that the `delete [] p` should be moved, but doesn't the `q.wait()` copy the data back; so `p[0]` should equal `9`?

**Comment by romanovvlad** [comment]
> 
> 
> Thanks. Yes, I see now that the `delete [] p` should be moved, but doesn't the `q.wait()` copy the data back; so `p[0]` should equal `9`?

No, it doesn't.

**Comment by pkeir** [comment]
Ok, I see. I had thought the required data movements would correspond to implicitly enqueued tasks on the queue.
