### ISSUE TITLE
Validate the scope of group-local variables definintion

### ISSUE THREAD

**Issue by mlychkov** [intel/llvm#3436]
Checking validity should somehow be addressed for group-local variables definintions.
It should be checked that `__sycl_allocateLocalMemory` (or its source form - `group_local_memory`) does not occur:
- in a function (other than user lambda/functor)
- in a loop
- in a non-convergent control flow

I think it is OK to occur in convergent if. Some execution paths will just not use the global created for the allocation.

But LLVM pass is not the best place to diagnose these cases. Error checking should be done in the front-end compiler.

_Originally posted by @kbobrovs in https://github.com/intel/llvm/pull/3329#discussion_r602459133_

**Comment by bader** [comment]
Based on email discussions the requested diagnostics are for the following cases:

* group_local_memory() is called in any scope other than outermost kernel scope
* group_local_memory() is called inside an if/loop (i.e. the scope is not function scope)

The first diagnostic cannot be implemented in the frontend. While we do some reachability analysis in the FE, we do not keep track of depth when doing deferred diagnostics. So "outermost scope of the kernel will not be feasible to diagnose".  Cases like this will be impossible to diagnose - 

```C++
struct S {
  void operator()(){
    group_local_memory();
  }
};

struct U {
  void operator()(){
    group_local_memory();
    S s;
    s();
  }
};

void foo() {
  single_task<class sycl_kernel1>(S{});
  single_task<class sycl_kernel2>(U{}); 
}
```

The second diagnostic can possibly be implemented. However limiting functionality in this way (and as requested by diagnostic 1) is a novel language design that requires significant justification because of how unusual it is. It can be argued that the openCL diagnostic this request is trying to emulate is not good design as well (https://godbolt.org/z/3Kb6cK91Y). However, the fact that OpenCL deals with variable declarations (as opposed to function calls), and additional requirements of SYCL make the requested DPCPP diagnostics objectively worse design.
