### ISSUE TITLE
[SYCL] Abort on non-uniform work-groups for reductions

### ISSUE THREAD

**Issue by masterleinad** [intel/llvm#3565]
**Describe the bug**
Reductions where the number of work items is divisible by the workgroup size fail to run with 
```
terminate called after throwing an instance of 'cl::sycl::nd_range_error'
  what():  Non-uniform work-groups are not supported by the target device -54 (CL_INVALID_WORK_GROUP_SIZE)
Aborted (core dumped)
```

**To Reproduce**
Compile
```C++
#include <CL/sycl.hpp>

int main() {
  auto sycl_queue = sycl::queue(sycl::default_selector());

  int N=4;
  using value_type = int;
  auto* x = sycl::malloc_device<value_type>(N, sycl_queue);
  auto* y = sycl::malloc_device<value_type>(N, sycl_queue);

  auto event_x = sycl_queue.memset(x, 0, N*sizeof(value_type));
  auto event_y = sycl_queue.memset(y, 0, N*sizeof(value_type));

  event_x.wait();
  event_y.wait();

  value_type result{};
  auto* result_ptr = sycl::malloc_device<value_type>(sizeof(result), sycl_queue);
    sycl_queue.submit([&](cl::sycl::handler &cgh) {
      auto reduction = cl::sycl::ONEAPI::reduction(result_ptr, std::plus<>());
      cgh.parallel_for(
        sycl::nd_range<1>(N, 8), reduction, [=](sycl::nd_item<1> itemId, auto& sum) {
          const int i = itemId.get_global_id();
          sum.combine(x[i]*y[i]);
        });
    });
  sycl_queue.wait();
  sycl_queue.memcpy(&result, result_ptr, sizeof(result));
  sycl_queue.wait();
  std::cout << "Result: " << result << std::endl;
};
```
via
```
clang++ -fsycl-targets=nvptx64-nvidia-cuda-sycldevice
```
and run. Even if this might be a problem with the underlying `OpenCL` backend, I would expect the compiler to handle this case gracefully and still do the reduction correctly. Otherwise, it's impossible to use the reduction interface if the number of work items is a large prime number.

**Environment:**

- OS: Linux
- NVIDIA GPU (but I would expect other targets using an older OpenCL version having the same problem).
- DPC++ version: 
 ```
$ clang++ --version
clang version 12.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/sycl/bin
```
- Dependencies version: CUDA 10.2

**Comment by masterleinad** [comment]
Also seeing this with `Intel(R) oneAPI DPC++/C++ Compiler 2021.2.0` printing
```
terminate called after throwing an instance of 'cl::sycl::nd_range_error'
  what():  Local work-group size {8, 1, 1} is greater than global range size {4, 1, 1}. Non-uniform work-groups are not allowed by default. Underlying OpenCL 2.x implementation supports this feature and to enable it, build device program with -cl-std=CL2.0 -54 (CL_INVALID_WORK_GROUP_SIZE)
```

**Comment by Pennycook** [comment]
This is by design, as SYCL does not support non-uniform work-group sizes: https://github.com/KhronosGroup/SYCL-Docs/pull/101.

The ND-range form of `parallel_for` is designed to be explicit, and if you want to set a specific work-group size then you have to account for divisibility in your lambda, something like:
```c++
range<1> rounded_N = (N + 7) / 8 * 8;
cgh.parallel_for(
  sycl::nd_range<1>(rounded_N, 8), reduction, [=](sycl::nd_item<1> itemId, auto& sum) {
  const int i = itemId.get_global_id();
  if (i < N) {
    sum.combine(x[i]*y[i]);
  }
});
```
I appreciate that you can't change the user's lambda in a framework like Kokkos, but the above should generalize to calling some user-provided functor instead of `sum.combine`.

If you just want a reduction kernel without specifying a work-group size, that's possible too: see https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:reduction.  Unfortunately, we don't support `reduction` objects for the non-ND-range form of `parallel_for` yet, but would that address your use-case?

Note that the non-ND-range form of `parallel_for` has a different execution model to the ND-range form (see https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_basic_data_parallel_kernels), which makes it legal for implementations to use non-uniform work-groups and other tricks as an implementation detail (e.g. to handle prime numbers cleanly).

**Comment by masterleinad** [comment]
> This is by design, as SYCL does not support non-uniform work-group sizes: [KhronosGroup/SYCL-Docs#101](https://github.com/KhronosGroup/SYCL-Docs/pull/101).

Thanks for the insight! I couldn't find that clearly in the SYCL 2020 specifications. Maybe, I'll have a look into that document in the future. :slightly_smiling_face: 

> I appreciate that you can't change the user's lambda in a framework like Kokkos, but the above should generalize to calling some user-provided functor instead of sum.combine.

Yes, as of now, we are using our own parallel_reduce implementation but I am interested in using the SYCL's/DPC++'s reduction interface if we can make it work for all use cases. This issue was not a road blocker but just something that seemed to be unintended.

> If you just want a reduction kernel without specifying a work-group size, that's possible too: see khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:reduction. Unfortunately, we don't support reduction objects for the non-ND-range form of parallel_for yet, but would that address your use-case?

Dropping the requirement of specifying a workgroup size would be a nice-to-have so we don't have to optimize for it.
