### ISSUE TITLE
[SYCL] event get_profiling_info problem 

### ISSUE THREAD

**Issue by agozillon** [intel/llvm#42]
So another contrived example:

```
#include <CL/sycl.hpp>
using namespace cl::sycl;

int main() {

  queue q{property::queue::enable_profiling()};
  auto e = q.submit([&](handler &cgh) {
      int w = 512;
      cgh.single_task<class event_wait>([=]() mutable {
        for (int i = 0; i < 512000; ++i)
          ++w;
      });
      printf("%d \n", w);
  });

  auto nsTimeEnd = e.get_profiling_info<info::event_profiling::command_end>();
  return 0;
}
```
So I have tried this with ComputeCPP (1.0) and the Intel SYCL (ISYCL) compiler in both cases using an Intel OCL selector. In ISYCL the get_profiling_info call will terminate in the SYCL runtime with the following diagnostic:

include/CL/sycl/detail/event_info.hpp:26: OpenCL API returns: -7 (CL_PROFILING_INFO_NOT_AVAILABLE)

Now if you put an explicit queue wait in, all is good in the world and it'll give a reasonable value! So, it seems that e.get_profiling_info is not a blocking call/implicit wait. And this leads to nondeterministic results in this case, some times it'll terminate, sometimes the events completed so you get your result back without problem.

However, the same snippet of code compiled with ComputeCPP seems to lead to a different result, without an explicit queue wait, it still yields a reasonable return value indicating that get_profiling_info is waiting on the event to complete before retrieving the information. 
 
I'm not sure which behavior is correct as far as the specification is concerned (I did skim and I don't think there is a rule specifying get_profiling_info forces a wait till event completion).  So this may be more of a specification related issue than an implementation issue, if that's the case I can move the issue.

**Comment by Ruyk** [comment]
See my answer to #41  re: wait on destruction.

ComputeCpp does wait on the event to obtain the profiling information, but that is implementation-defined.

**Comment by agozillon** [comment]
Thank you very much @Ruyk I'll have a look at both of the issues I opened up again and ask to close them/close if necessary!

**Comment by keryell** [comment]
After discussing with @agozillon and looking at OpenCL 2.2-10 specification, I think there is an issue in the SYCL specification because it is undefined behavior while there are some useful alternative.

The alternative I can see:
- call `std::terminate` if the information is not available;
- throw an exception if the information is not available;
- remove this API and just rely on OpenCL interoperability layer to get this information;
- wait for the information to be available, which is the only the real use case for me because if the programmer is asking for some information I guess she is really interested by this information...

Waiting for the queue at large is too strong to me because it means to wait also for all the kernels in flight in the queue.

**Comment by Ruyk** [comment]
We can discuss and clarify that on Khronos IP zone. For the record, ComputeCpp only waits for the chain of events associated with the given profiling event, not for the entire queue submission.

**Comment by agozillon** [comment]
Can close this I believe after merge of: https://github.com/intel/llvm/pull/168 and the added clarifications in the SYCL specification?

**Comment by bader** [comment]
@Ruyk, @keryell are you okay with closing this?

**Comment by keryell** [comment]
Yes, I am good about closing this as solved.
