### ISSUE TITLE
[SYCL] Add device-side intrinsic to check for pointer address space

### ISSUE THREAD

**Issue by kbobrovs** [intel/llvm#422]
After moving to "default generic" approach for pointers, when most of the pointers in the LLVM IR generated by FE point to generic address space, there must be a way to check for a generic pointer's address space in the generated code before it is handed off to a back-end.

As an example, hierarchical parallelism in presence of generic pointers requires dynamic checking if a pointer is private or not - see https://github.com/intel/llvm/issues/421

This intrinsic should be a part of the abstraction layer requested here::
https://github.com/intel/llvm/issues/253

**Comment by kbobrovs** [comment]
Possible variants:

1) the most basic variant (which seems enough for hierarchical parallelism improvement) - it just tests whether the pointer is to private AS; is probably implementable on wider range of devices than the generic form:
```declare i1 @__spirv_is_private_address_space(i8 addrspace(4)* nocapture <ptr>)```

2) fully-functional
Form1:
- ```declare i8 @__spirv_get_address_space_<AS>(i8 addrspace(AS)* nocapture <ptr>)```
this form does not mandate particular AS for the input pointer. If AS is concrete then the call evaporates to compile-time constant representing the AS, if it is generic - the runtime will determine the concrete AS and return it
Form2:
- ```declare i1 @__spirv_is_in_address_space(i8 addrspace(4)* nocapture <ptr>,  i8 <AS_id>)```
tells if given pointer points to given address space, the second argument must be a compile-time constant 0, 1 or 3

It is not clear what to do for targets which can not support dynamic checks. Maybe rely on AS inference and fail compilation if concrete AS wasn't inferred for the pointer intrinsic argument.

**Comment by Naghasan** [comment]
I think https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpGenericCastToPtrExplicit covers more or less what you need here.

i case you have plans to provide a SYCL level function to perform the test `__spirv_is_private_address_space`. May I point out that directly providing to the user the capability to test and then convert generic pointers may have an adverse effect on type deduction. For example, if I do:
```
generic int * i = ...;
if (sycl::is_global(i)) {
  sycl::global_ptr<int> ptr(i);
  // use ptr
} else {
  if (sycl::is_local(i)) {
    sycl::local_ptr<int> ptr(i);
    // use ptr
  }
}
```
We cannot create a scope that increase the knowledge on `i` regarding its address space, therefore it is difficult (in the general case) to allow the construction of the multi pointer objects.

This is toy example, a solution is trivial here, but it is easy to bury the conversion deeper in the call graph making the tracking way more difficult.

But, if we provide a conversion function rather than a testing function, we let the implementation the choices on how to handled it internally. Concretely for the user, he would write something like:
```
generic int * i = ...;
if (sycl::optional<sycl::global_ptr<int>> ptr = sycl::get_as_global(i)) {
  // use ptr
} else {
if (sycl::optional<sycl::local_ptr<int>> ptr = sycl::get_as_local(i)) {
    sycl::local_ptr<int> ptr(i);
    // use ptr
  }
}
```
where `sycl::optional<sycl::multi_ptr<int, address_space>>` can be converted to bool, returning true if the conversion succeeded or false if it failed.

It does not change much from the code above, but it is much more nicer for implementations.
