### ISSUE TITLE
[SYCL] Named parallel for and anonymous class doesn't compile

### ISSUE THREAD

**Issue by TApplencourt** [intel/llvm#4725]
**Describe the bug**

Hi, 

First apology for my probably poor comprehension of C++. 

In the reproducer below we create a templated anonymous class that will be used to create a name for our `parallel_for`.
This code is not compiling and give a `declaration of anonymous class must be a definition`  error (see full log below).

This code was compiling is olders versions of dpcpp for example`2021.x.0.20210323` . 

**To Reproduce**
```
$cat bug.cpp
#include <CL/sycl.hpp>
using namespace cl::sycl;
template <typename F>
class KernelOp;

template <typename F>
void index_op_kernel(queue& q, F&& op) {
    {
        using kname = KernelOp<decltype(op)>;
#ifndef BUGWA
        q.parallel_for<kname>(range<1>(10), [=](id<1> idx) {});
#else
        q.parallel_for(range<1>(10), [=](id<1> idx) {});
#endif
    }
}

int main(int argc, char **argv) {
    sycl::queue q = queue( default_selector{} );
    index_op_kernel(q, [=](int i) { return i*i; });
    q.wait();
}
tapplencourt@arcticus13:~/tmp> dpcpp bug.cpp
In file included from <built-in>:1:
/tmp/lambda_kname_param_min-header-569e8f.h:7:1: error: declaration of anonymous class must be a definition
class;
^
/tmp/lambda_kname_param_min-header-569e8f.h:7:1: warning: declaration does not declare anything [-Wmissing-declarations]
/tmp/lambda_kname_param_min-header-569e8f.h:37:79: error: unknown type name 'lambda'
template <> struct KernelInfo<::sycl::detail::__pf_kernel_wrapper<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>>> {
                                                                              ^
/tmp/lambda_kname_param_min-header-569e8f.h:37:86: error: expected ')'
template <> struct KernelInfo<::sycl::detail::__pf_kernel_wrapper<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>>> {
                                                                                     ^
/tmp/lambda_kname_param_min-header-569e8f.h:37:78: note: to match this '('
template <> struct KernelInfo<::sycl::detail::__pf_kernel_wrapper<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>>> {
                                                                             ^
/tmp/lambda_kname_param_min-header-569e8f.h:37:125: error: expected expression
template <> struct KernelInfo<::sycl::detail::__pf_kernel_wrapper<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>>> {
                                                                                                                            ^
/tmp/lambda_kname_param_min-header-569e8f.h:53:43: error: unknown type name 'lambda'
template <> struct KernelInfo<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>> {
                                          ^
/tmp/lambda_kname_param_min-header-569e8f.h:53:50: error: expected ')'
template <> struct KernelInfo<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>> {
                                                 ^
/tmp/lambda_kname_param_min-header-569e8f.h:53:42: note: to match this '('
template <> struct KernelInfo<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>> {
                                         ^
/tmp/lambda_kname_param_min-header-569e8f.h:53:89: error: expected expression
template <> struct KernelInfo<::KernelOp<(lambda at lambda_kname_param_min.cxx:16:24) &&>> {
                                                                                        ^
1 warning and 7 errors generated.
```
**Environment (please complete the following information):**

- OS: Linux
- DPC++ version: 2021.x.0.20210819

**Additional context**

Compiling with `-DBUGWA`, make the code work.

**Comment by rarutyun** [comment]
As my colleagues already pointed out you cannot use lambdas as the kernel name (or the part of kernel name) Basing on that you have two options (not necessary exclusive) to proceed further:
 - Use unnamed kernel calls
 - Use named kernel calls
     -  always
     -  just for debugging (in that case I would recommend to write compile-time dispatching to pass the kernel name to call when it is not default.

Of course, if you choose to the option 2.1 with always naming a kernel you basically would always need to pass it directly and make sure it's unique. This sub-option is mutually exclusive with the rest.

Making the choice with using unnamed kernels + named kernels just for the sake of debugging is probably wiser (but really depends on the use-case) but it would require you to write some smarter dispatching underneath because you **cannot** effectively write something like this:

```cpp
template <typename KernelName = my::some_name, typename F>
void index_op_kernel(queue& q, F&& op) {
    q.parallel_for<KernelName>(range<1>(10), [=](id<1> idx) {});
}

int main(int argc, char **argv) {
    sycl::queue q(default_selector{});
    index_op_kernel(q, [=](int i) { return i * i; }); // 1
    index_op_kernel(q, [=](int i) { return i + i; }); // 2
    q.wait();
}
```

because when always passing ``KernelName`` as the name as is for the example above calls 1 and 2 would give you the same name for the different template instantiation, in other words, redefinition.

So, as I said some compile-time dispatching would be required to solve this. There several techniques to enable this and I cannot say for sure which one to choose. It also depends on the use-cases.

Hope it's helpful, if you have further questions or you need specific suggestions about compile-time dispatching please let me know.
