### ISSUE TITLE
[CUDA] CTS atomic tests fail with unresolved extern function '_Z22__spirv_AtomicExchangePU3AS1fN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagEf'

### ISSUE THREAD

**Issue by yuxianch** [intel/llvm#5096]
**Describe the bug**
CTS atomic tests fail with unresolved extern function '_Z22__spirv_AtomicExchangePU3AS1fN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagEf' on Linux with CUDA backend

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and  https://github.com/KhronosGroup/SYCL-CTS/commit/b61c52a950b5974f2c6e96a759e3af64b6ef6b4b
2. Build CTS tests
```
cd SYCL-CTS
mkdir build && cd build
cmake -G "Ninja" -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -DOpenCL_LIBRARY=<path to built sycl>/lib/libOpenCL.so -DOpenCL_INCLUDE_DIR=<path to built sycl>/include/sycl -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-fsycl -fsycl-unnamed-lambda -Wno-deprecated-declarations" -DINTEL_SYCL_FLAGS="-fsycl-device-code-split=per_kernel" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja test_atomic
```
Error message:
```
FAILED: bin/test_atomic
: && <path to built sycl>/bin/clang++ -DSYCL2020_DISABLE_DEPRECATION_WARNINGS -ffp-model=precise  -fsycl -fsycl-unnamed-lambda -Wno-deprecated-declarations      -Wl,-no-relax    -fsycl -sycl-std=2020 -fsycl-device-code-split=per_kernel -fsycl-targets=nvptx64-nvidia-cuda tests/atomic/CMakeFiles/test_atomic_objects.dir/atomic_api_32.cpp.o tests/common/CMakeFiles/main_function_object.dir/main.cpp.o -o bin/test_atomic  -Wl,-rpath,<path to built sycl>/lib util/libutil.a oclmath/liboclmath.a <path to built sycl>/lib/libOpenCL.so && :
ptxas fatal   : Unresolved extern function '_Z22__spirv_AtomicExchangePU3AS1fN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagEf'
llvm-foreach:
ptxas fatal   : Unresolved extern function '_Z22__spirv_AtomicExchangePU3AS3fN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagEf'
llvm-foreach:
clang++: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 14.0.0 (https://github.com/intel/llvm.git e560dfe88ee69b3de4a5fe5472382defba19cee0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: <path to built sycl>/bin
clang++: note: diagnostic msg: Error generating preprocessed source(s).
ninja: build stopped: cannot make progress due to previous errors.
```
The unresolved function is declared in ./include/CL/__spirv/spirv_ops.hpp.
```
$ c++filt _Z22__spirv_AtomicExchangePU3AS3fN5__spv5Scope4FlagENS1_19MemorySemanticsMask4FlagEf
__spirv_AtomicExchange(float AS3*, __spv::Scope::Flag, __spv::MemorySemanticsMask::Flag, float)
```

**Environment**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git e560dfe88ee69b3de4a5fe5472382defba19cee0
- CUDA version: 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
```

**Comment by yuxianch** [comment]
The same failure is also seen on Windows when running CTS atomic tests.

**Comment by skosnits** [comment]
Similar in case of new test: sycl_cts/build_test_optional_kernel_features

`clang++ -DSYCL2020_CONFORMANT_APIS -DSYCL2020_DISABLE_DEPRECATION_WARNINGS -D__SYCL_DISABLE_PARALLEL_FOR_RANGE_ROUNDING__ -ffp-model=precise      -Wl,-no-relax    -fsycl -sycl-std=2020 -fsycl-device-code-split=per_kernel -Wno-deprecated-declarations -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda tests/optional_kernel_features/CMakeFiles/test_optional_kernel_features_objects.dir/kernel_features_mismatched_nd_range_exception.cpp.o tests/optional_kernel_features/CMakeFiles/test_optional_kernel_features_objects.dir/kernel_features_separate_unit.cpp.o tests/common/CMakeFiles/main_function_object.dir/main.cpp.o -o bin/test_optional_kernel_features  -Wl,-rpath<path to built sycl>/lib util/libutil.a oclmath/liboclmath.a vendor/Catch2/src/libCatch2.a <path to built sycl>/lib/libOpenCL.so -lpthread && :
ptxas fatal   : Unresolved extern function '_Z18__spirv_AtomicIAddPyN5__spv5Scope4FlagENS0_19MemorySemanticsMask4FlagEy'
llvm-foreach: 
clang++: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 15.0.0 (https://github.com/intel/llvm.git 1fe5eaa7455f25a1475794bedc42cc73e9b07bd1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: <path to built sycl>/bin
clang++: note: diagnostic msg: Error generating preprocessed source(s).
ninja: build stopped: cannot make progress due to previous errors.`

**Comment by t4c1** [comment]
These are two different issues. The original one with `test_atomic` is addressed by the pulll request linked above. The second one with `sycl_cts/kernel_features_mismatched_nd_range_exception` is a bug in the libclc remangler that is fixed as a part of https://github.com/intel/llvm/pull/5849
