### ISSUE TITLE
[DPC++] capture 'this' pointer in the kernal function

### ISSUE THREAD

**Issue by Maccchiatooo** [intel/llvm#6171]
When I want to capture the this pointer or outside variable in DPC++ code, I have to write it in my lambda function explicitly

```
    class abc{
    queue Q{};
    std::array<int, constsize> e;
    std::array<double, constsize>t;
    abc(){
    ua = malloc_shared<double>(local_size, this->Q);
    }
    
    void b();
    
  }

 void abc::b(){
      for(int i=0;i<constsize;i++){
      e[i]=i;
      t[i]=2*i; 
      }

    buffer<int> ee{e};
    buffer<double> tt{t};
auto ini2 = this->Q.submit([&,uq=this->ua](handler &h)
            { accessor eee{ee, h, read_only};
              accessor ttt{tt, h, read_only};
                                        
              h.parallel_for(range{size1, size2, size3}, [=](id<3> idx)
              double eu=uq[id[0]];
              int aa=eee[id[1]];
              double cc=ttt[id[2]];
             }

 }
```
But, now I have a lot of variables that need to be captured in the lambda function, do I have to use the same method to write them explicitly? Or there are some other tricks to make this?

I run my code on ThetaGPU.
The system information is: #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021
The GPU I use is: Selected device:NVIDIA A100-SXM4-40GB
I am not quite sure about the DPC++ or OneAPI version, but it is for Ubuntu 18.04.

**Comment by zjin-lcf** [comment]
I have a question. How do you pass a lot of variables in your CUDA program ?

**Comment by Maccchiatooo** [comment]
I am not sure exactly how DPC++ does that, but I do like "h.parallel_for(range{llx, lly, llz}, [=, fq = this->f, uq = this->ua, vq = this->va, wq = this->wa, pq = this->p, rhoq = this->rho](id<3> idx)
                                                   {"

**Comment by zjin-lcf** [comment]
Not a fan of C++ lambda, I wonder if the following works.

auto ini2 = this->Q.submit([&](handler &h)
            { accessor eee{ee, h, read_only};
              accessor ttt{tt, h, read_only};
               **fq = this->f;
               uq = this->ua;
                ...
               rhoq = this->rho;**             
              h.parallel_for(range{size1, size2, size3}, [=](id<3> idx)
              double eu=uq[id[0]];
              int aa=eee[id[1]];
              double cc=ttt[id[2]];
             }

**Comment by Maccchiatooo** [comment]
I think it should work, but then I still need to declare a lot of new parameters. I try to capture [*this] in the parallel for, but then I have the error the value is not a device copyable type.  I am not sure if I can transfer ua = malloc_shared<double>(local_size, this->Q); to a device copyable type?

**Comment by zjin-lcf** [comment]
I hope C++ experts could answer your question.

**Comment by nliber** [comment]
As of C++17 (so valid for DPC++), `[*this]` will capture a copy of the current object.

However, any object copied to the kernel must be device copyable.  For most types, that effectively means they must be [TriviallyCopyable](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable).

`malloc_shared` is just a way to allocate memory.  You can capture the `ua` pointer (pointers themselves are trivially copyable), but I don't think that is the question you are asking.

In general, the only way objects are transferred between a host and device is by copying the bits, so if the copy/move constructor/assignment operator does anything else, or the destructor isn't a noop, then you are invoking undefined behavior.  (The more precise constraints on TriviallyCopyable and Device Copyable are so that this all fits into the C++ and SYCL object models.)

**Comment by AlexeySachkov** [comment]
@Maccchiatooo, do you have any other questions about the value not being device copyable type? I believe that @nliber has explained the situation here. Moreover, if your type is not automatically detected as device copyable, but you believe that it matches the requirements, you can explicitly specialize [`is_device_copyable`](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_is_device_copyable_type_trait) type trait for your type.
