### ISSUE TITLE
Test Nvidia Tensor Core Example Failed

### ISSUE THREAD

**Issue by malixian** [intel/llvm#6177]
There is a runtime exception when run the compiled code from llvm/sycl/test/check_device_code/matrix/matrix-nvptx-bf16-test.cpp.

Compile Command is:  _clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --cuda-gpu-arch=sm_80  -DSYCL_EXT_ONEAPI_MATRIX=3 matrix-nvptx-bf16-test.cpp -o matrix-nvptx-bf16-test.out_

And run this binary we will get the error: **what():  Attempt to set multiple actions for the command group. Command group must consist of a single kernel or explicit memory operation. -59 (CL_INVALID_OPERATION)**

**Comment by JackAKirk** [comment]
This test is not intended to be run through the runtime and it is not valid runtime code, therefore this is expected behaviour
This is a device code test only intended to check that the correct device code is emitted for the executed functions. 

Please see this runtime integration test that includes bf16 cases (via uint16_t). The explicit bfloat16 type is employed in an update of this test (dependent on https://github.com/intel/llvm/pull/5964) that has not been merged yet: https://github.com/intel/llvm-test-suite/pull/975/files#diff-cf5fef92e0bbd992f77bb2ac6e391710d2ae4fd795aa266eed56f922f30cdd3f

**Comment by malixian** [comment]
It's a very useful answer, thanks!!
