### ISSUE TITLE
CUDA Supported, but no CPU Support

### ISSUE THREAD

**Issue by e404044** [intel/llvm#6686]
I followed the instructions to build sycl_environment for cuda support and it worked. 

[16:16]ec2-user$ ./device_selector-gpu.exe
Selected device: Tesla V100-SXM2-16GB
 -> Device vendor: NVIDIA Corporation

But per the sycl-ls output below, there's no CPU and when i tell my device selector program to target the CPU, it can't find it.  Is there a way to add CPU capabilities while building for CUDA? 

`[15:59]ec2-user$ sycl-ls --verbose
[ext_oneapi_cuda:gpu:0] NVIDIA CUDA BACKEND, Tesla V100-SXM2-16GB 0.0 [CUDA 11.6]
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]

Platforms: 2
Platform [#1]:
    Version  : CUDA 11.6
    Name     : NVIDIA CUDA BACKEND
    Vendor   : NVIDIA Corporation
    Devices  : 1
        Device [#0]:
        Type       : gpu
        Version    : 0.0
        Name       : Tesla V100-SXM2-16GB
        Vendor     : NVIDIA Corporation
        Driver     : CUDA 11.6
Platform [#2]:
    Version  : 1.2
    Name     : SYCL host platform
    Vendor   :
    Devices  : 1
        Device [#0]:
        Type       : host
        Version    : 1.2
        Name       : SYCL host device
        Vendor     :
        Driver     : 1.2
default_selector()      : gpu, NVIDIA CUDA BACKEND, Tesla V100-SXM2-16GB 0.0 [CUDA 11.6]
host_selector()         : host, SYCL host platform, SYCL host device 1.2 [1.2]
accelerator_selector()  : No device of requested type available. -1 (PI_ERRO...
cpu_selector()          : No device of requested type available. -1 (PI_ERRO...
gpu_selector()          : gpu, NVIDIA CUDA BACKEND, Tesla V100-SXM2-16GB 0.0 [CUDA 11.6]
custom_selector(gpu)    : gpu, NVIDIA CUDA BACKEND, Tesla V100-SXM2-16GB 0.0 [CUDA 11.6]
custom_selector(cpu)    : No device of requested type available. -1 (PI_ERRO...
custom_selector(acc)    : No device of requested type available. -1 (PI_ERRO...
`

**Comment by JJOL** [comment]
Hi e404044,

Have you already tried following the Install Low Level Runtime subsection of "Use DPC++ toolchain" in the Getting Started Guide?
https://intel.github.io/llvm-docs/GetStartedGuide.html#use-dpc-toolchain

I found that is necessary to complete this steps, particularly install the OpenCL runtime for CPU and link the TBB libraries in order to get the application to run in CPU's and be able to compile AOT.

After doing it this command works for me:
clang++ -fsycl -fsycl-targets=spir64_x86_64 main.cc

Hope this works for you.

**Comment by AlexeySachkov** [comment]
Hi @e404044,

> How does installing the OpenCL runtime for CPU interoperate with opencl-aot? 

`opencl-aot` is a simple OpenCL application, which calls `clCreateProgramWithIL`, then `clBuildProgram` and then `clGetProgramBuildInfo` to extract the resulting binary. You can find it source code within this repo: https://github.com/intel/llvm/tree/sycl/opencl/opencl-aot

> The instructions said “CPU AOT compiler opencl-aot is enabled by default.” How is it enabled by default?

I assume that the instruction wants to say that `opencl-aot` will be built by default when you build SYCL compiler from sources. We should probably clarify our documentation to avoid that confusion.

> I don’t think I have that executable anywhere installed after following the instructions for adding CPU low level runtime.

That's expected, because the tool is a part of SYCL compiler, not a part of OpenCL CPU runtime.

> Also after installing the runtime, the instructions recommend running the buildbot/check.py script. What output should one look for to know that the check.py is testing OpenCl interoperability?

Honestly, for that purpose I would recommend launching your own test/app which uses OpenCL interoperability. `buildbot/check.py` launches unit-tests for the compiler and those are written in assumption that we have zero low-level runtimes available and therefore I wouldn't expect it to have a lot of coverage for OpenCL interoperability.

**Comment by e404044** [comment]
@AlexeySachkov thanks that's helpful. all good now!
