### ISSUE TITLE
[CI] CUDA LLVM Test suite run hangs

### ISSUE THREAD

**Issue by alexbatashev** [intel/llvm#6732]
CUDA test suite run in CI seems to hang: https://github.com/intel/llvm/runs/8243569878?check_suite_focus=true

ATM it is at 4.5 hours, while locally it is usually under 5 minutes.

Not sure how to reliably reproduce this issue, but everything appears to be OK if run locally.

<img width="1536" alt="Снимок экрана 2022-09-08 в 14 47 01" src="https://user-images.githubusercontent.com/829678/189118132-50f959b5-984c-4e42-b67e-57cfced3ec25.png">

**Comment by ldrumm** [comment]
Apologies for the delay. The logs are no longer available, and we don't seem to have any CUDA tests hanging in CI recently.

I understand that some of the tests were XFAIL, so it doesn't necessarily mean any issue was fixed. That said - if you can reproduce this hang with a new testcase, please re-open this ticket with a reproducer - otherwise I don't think there's much more we can do to move this ticket along
