### ISSUE TITLE
[SYCL][CUDA] negate operation

### ISSUE THREAD

**Issue by zjin-lcf** [intel/llvm#6958]
For r = - (h1 + h2), the PTX code is

        add.rn.f16      %h3, %h1, %h2;
        mov.b16         %rs1, %h3;
        xor.b16         %rs2, %rs1, -32768;

neg.f16 may be a substitute for the last two instructions.

**Comment by jchlanda** [comment]
I've created a PR in upstream LLVM: https://reviews.llvm.org/D135428

**Comment by zjin-lcf** [comment]
Thanks.

**Comment by Artem-B** [comment]
> neg.f16 may be a substitute for the last two instructions.

Generally speaking, what really needs to be fixed here is allowing more i16 ops to use fp16 arguments. On PTX level fp16 registers use .b16 type and integer ops should accept them directly w/o issues. We could just pattern-match fp16->i16 conversion during lowering and just pass the argument through.

However, I think that will be just a cosmetic change that will make no difference on the actual GPU code.

`mov` will eventually be a no-op in SASS (fp and integer operands use exactly same registers and ptxas does a good job eliminating unnecessary moves), so on the SASS level we're trading-off HADD for LUT (which does XOR) and it's not immediatelly obvious which one would be faster. Having some benchmarks would be very helpful. 

My bet is that xor will be comparable to HADD on modern GPUs, though it may vary across architectures. Older GPU variants had much slower integer performance, but those didn't have FP16 either, so it does not matter.

On the other hand, having FTZ variant may be useful for keeping denormals flushing consistent with FP32. That may be a good enough reason even if it turns out that xor may be a bit faster.

**Comment by zjin-lcf** [comment]
Thank you for replying the issue with an in-depth explanation. Please create a feature request "allowing more i16 ops to use fp16 arguments." if that will improve performance/portability.
