### ISSUE TITLE
Question: Why is it no longer possible to filter the default device selector to execute on the host device ?

### ISSUE THREAD

**Issue by Ralender** [intel/llvm#7292]
I usually use the default_device selector and with the proper export SYCL_DEVICE_FILTER to execute on device
and add a SYCL_DEVICE_FILTER=host when debugging on cpu.
but now I receive this message.
```
WARNING: The 'host' backend type is no longer supported in device filter.
```

**Comment by AlexeySachkov** [comment]
Hi @Ralender, `host` device is not a part of SYCL 2020 spec and has never been fully functional in terms of scope of supported features. Therefore, we decided to completely drop support for it

**Comment by Ralender** [comment]
so how are we supposed to debug SYCL application. if we cant execute then on CPU in the debugger ?

**Comment by zjin-lcf** [comment]
Do you want to debug a GPU application on a CPU ?

**Comment by Ralender** [comment]
> Do you want to debug a GPU application on a CPU ?

it was mostly FPGA kernels but yes this is what i used to do.

**Comment by keryell** [comment]
@zjin-lcf that is the idea of SYCL as a pure C++ implementation compared to CUDA, HIP...
It should be possible to debug almost everything on CPU cores and you can use UBsan, thread-sanitizer, adress-sanitizer, Valgrind/Helgrind, your favorite CPU debugger or checker, etc. This is a huge advantage for productivity, debug, porting.
Since on CPU you might have arbitrary code in SYCL kernels, like OS system-call, virtual functions, RPC, cloud-invocation, Python interpreter, whatever, it is even more useful to debug or to port incrementally some existing CPU code to SYCL accelerated code, compared to debugging directly on GPU or FPGA for example.

**Comment by keryell** [comment]
@AlexeySachkov a not supported but existing feature is better than nothing at all. :-)
The concept of host device has been superseded by a device with the aspect `host_debuggable`. I guess the previous implementation should be recycled and improved for this? @bader
@illuhad Otherwise we can use hipSYCL instead or you can include the hipSYCL implementation.
The host device is also a reason why I still use the legacy triSYCL for my experiments.
Since C++ has coroutines now, they could be used to speed-up the work-group barriers if this was the limitation.
But the future is to use hierarchical parallelism and not the barriers anyway.

**Comment by AlexeySachkov** [comment]
> so how are we supposed to debug SYCL application. if we cant execute then on CPU in the debugger ?

Why so? I'm sure it is not entirely bug-free, but debugging on both GPU & CPU is supported: [documentation link first](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-debugging-dpcpp-linux/top.html), [documentation link second](https://www.intel.com/content/www/us/en/develop/documentation/debugging-dpcpp-linux/top/debug-a-sycl-application-on-a-cpu.html).

>  This is a huge advantage for productivity, debug, porting.
Since on CPU you might have arbitrary code in SYCL kernels, like OS system-call, virtual functions, RPC, cloud-invocation, Python interpreter, whatever

SYCL spec explicitly prohibits calling virtual functions from SYCL kernels regardless of the device. So, with the current spec wording it doesn't seem like a SYCL kernel can have an arbitrary code even if it is targeted for CPU. `host_task` is something that can execute arbitrary code.

**Comment by Ralender** [comment]
> > so how are we supposed to debug SYCL application. if we cant execute then on CPU in the debugger ?
> 
> Why so? I'm sure it is not entirely bug-free, but debugging on both GPU & CPU is supported: [documentation link first](https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-debugging-dpcpp-linux/top.html), [documentation link second](https://www.intel.com/content/www/us/en/develop/documentation/debugging-dpcpp-linux/top/debug-a-sycl-application-on-a-cpu.html).
> 

Thanks for the information.
What I mean by on CPU was AOT compiled to the CPU not OpenCL on cpu. because you cant use all the tools you know on OpenCL and you need an installed OpenCL implementation for cpu. the debugger has to be costume because of this.

**Comment by keryell** [comment]
@AlexeySachkov it looks like the CPU debugging you are talking about is going through OpenCL, which is not user-friendly to execute arbitrary code in kernels for incremental porting or debugging purpose, use tools like UBsan, ThreadSanitizer or whatever open-source tooling.
Recently at SuperComputing @jamesreinders was also mentioning such use cases during the SYCL tutorial.
When the concept of host device has been removed from the SYCL 2020 it was not to forbid such an implementation but to allow some almost CPU-less platforms to pass the CTS because they have powerful accelerators. For usual x86-like CPU platforms, it should not be the case and the CPU should run on SYCL kernels just using a library-only C++ implementations.
Is it possible to reverse the removal or allow it with some compilation options?
I have created internal Khronos issue https://gitlab.khronos.org/sycl/Specification/-/issues/634 to discuss about the QoI consequences of this.

**Comment by Ralender** [comment]
To clarify it has never been convenient (to my knowledge) to run sanitizers for SYCL applications. because the sanitizers requires an exact match between the compiler and the runtime library and the SYCL library is built from the system compiler while the SYCL applications are build from the SYCL compiler. which will require different versions of sanitizers.

**Comment by AlexeySachkov** [comment]
I have not heard of any plans to return `host` device in the form we had it and I very much doubt that it would ever happen.

However, we do have some kind of a replacement here, which is [native CPU device](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/SYCLNativeCPU.md). The doc I've linked is a design doc and not a user manual, though. The idea here is that we compile the device code as a regular host C++ code and can execute it on a host CPU without any dependencies like OpenCL.

Tagging @intel/dpcpp-nativecpu-pi-reviewers in case folks know of any user manual for this target/backend and can provide more information about its status.

I will close the issue, because the answer to the original question was provided. In case of any further questions about native CPU target/backend, please open a new discussion/issue and we will take a look.
