### ISSUE TITLE
why sha256sum changes when compiler the same program twice

### ISSUE THREAD

**Issue by guoyejun** [intel/llvm#7385]
sha256sum of 'a.out' changes when compiler the same program twice with same option

no matter what the program is, 
$ dpcpp -O2 -g trydpcpp.cpp
$ sha256sum a.out
70069a95e68870cdab5ba915b0d91d3492a3c7592a3befa1b060b4a57703fa0b  a.out
$ dpcpp -O2 -g trydpcpp.cpp
$ sha256sum a.out
a13654be008b447edb4b518831bcad3a30fae7fb37bb8b9b223b1e25a953b8b9 a.out

I tried a normal c++ program with g++, and the sha256sum of a.out is always the same.

**Comment by zjin-lcf** [comment]
They are also different with the nvcc compiler

**Comment by guoyejun** [comment]
could you share why it is different? thanks.

**Comment by AlexeySachkov** [comment]
Thanks for the observation, @guoyejun!

I don't know the exact reason of why the hash changes, but DPC++ compilation flow is more complicated than a regular C++ compilation flow and most likely at some step we are inserting something non-deterministic.

My best guess would be that this is caused by integration footer we add: we generate a temporary file, which has a random name and we compile that file instead of your original input. When debug info is enabled, the filename is incorporated into the binary and it changes hash. Integration footer was introduced to implement features like [SYCL 2020 specialization constants](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_specialization_constants) and [`sycl_ext_oneapi_device_global`](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_device_global.asciidoc) extension. You can find technical design description [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/SYCL2020-SpecializationConstants.md#design)

To confirm or disprove that we can try the following experiments:
- try to disable integration footer by passing `-fno-sycl-use-footer` option to the compiler
- try to disable debug info generation by omitting `-g` flag

My current guess is that only combination of integration footer + debug info triggers non-deterministic binaries. Disabling one of those should allow to workaround that. There was a proposal to redesign that part of the implementation to remove integration footer, but it is postponed for now (#5910)

**Comment by guoyejun** [comment]
thanks @AlexeySachkov !

I found that both of them are needed, the checksum is the same with:
dpcpp -O2 -fno-sycl-use-footer  trydpcpp.cpp

**Comment by AlexeySachkov** [comment]
> I found that both of them are needed, the checksum is the same with:
dpcpp -O2 -fno-sycl-use-footer trydpcpp.cpp

That's interesting, it actually means that even if no debug info is requested, we still emit some non-deterministic data which is encoded into binaries

**Comment by guoyejun** [comment]
yes, and the file size is still the same even the checksum is different.

**Comment by guoyejun** [comment]
thanks, it is useful when we compare the .so file in different systems for debugging.
