### ISSUE TITLE
PI unittests fail when no OpenCL RT is available

### ISSUE THREAD

**Issue by smaslov-intel** [intel/llvm#739]
> Great thanks for doing this! The PI tests will be build always, but when/how are they run?

@smaslov-intel  This now works as in Clang and the other LLVM projects: 
* When SYCL testing is enabled with the CMake flag [`SYCL_INCLUDE_TESTS`](https://github.com/intel/llvm/pull/585/files#diff-0665cb0e6f161edd2ede910c193ce25aR33) then the unittests are added as a dependency to the LIT tests (see CMake variable [`SYCL_TEST_DEPS`](https://github.com/intel/llvm/pull/585/files#diff-ad9ca624b2a795a5f24145a17c806d1fR174)).
* This in itself ensures that the unittests are build when the other LIT tests are build, e.g., by running the build for the `check-sycl` target.
* The LIT tests folder now has a `Unit` sub-folder which contains [LIT config files that are gtest aware](https://github.com/intel/llvm/pull/585/files#diff-bae064f44036fce782bfe2521b5ac110R24) and are pointed to the unittests build directory to discover all included test executables to run.

_Originally posted by @bjoernknafla in https://github.com/intel/llvm/pull/585#issuecomment-539951062_

**Comment by bjoernknafla** [comment]
How urgent is this problem? Is this breaking automatic testing?

Introducing PI backend discovery to the PI unittests would automatically deal with not finding any platforms and devices. My guess is that it will look like the unittests passed even though not a single one ran.

I dislike how this can hide problems though, e.g., if the lookup mechanism for PI plugins fails the testing would still look ok instead of failing to warn about the problem.

I need to think a bit more about this. Any feedback and thoughts are highly welcome how to ensure solid testing.

**Comment by smaslov-intel** [comment]
Yes, this is breaking the testing that is legally performed on machines not having the full run-time setup.

> if the lookup mechanism for PI plugins fails the testing would still look ok instead of failing to warn about the problem.

I think we should just separately test for PI discovery to work correctly, which is TBD.

**Comment by bjoernknafla** [comment]
See PR for a fix: https://github.com/intel/llvm/pull/748

**Comment by AlexeySachkov** [comment]
@smaslov-intel, looks like fix was provided, can we close this issue?

**Comment by smaslov-intel** [comment]
Yes
