### ISSUE TITLE
[SYCL] Question : where to get sycl.lib?

### ISSUE THREAD

**Issue by ThomsonTan** [intel/llvm#752]
Probably a trivial question, I am trying follow below doc and the sample program. But I got link error like `sycl.lib` cannot be found. Where can I this this lib?

https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md

**Comment by ThomsonTan** [comment]
Thanks @alexbatashev . I have a naive question. As per below section, `cmake` runs for source dir `%SYCL_HOME%\llvm\llvm`, but how is `%SYCL_HOME%\llvm\sycl` included by the build system. I followed the steps but didn't get any sycl build. Wondering any part I am missing.

https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md#build-sycl-toolchain

**Comment by ThomsonTan** [comment]
Never mind, seems I missed typed parameter to cmake.

It appears that SYCL depends on `cl_khr_il_program` which is not supported on my local devices. Is this only for some graphics card?

**Comment by alexbatashev** [comment]
> Thanks @alexbatashev . I have a naive question. As per below section, `cmake` runs for source dir `%SYCL_HOME%\llvm\llvm`, but how is `%SYCL_HOME%\llvm\sycl` included by the build system. I followed the steps but didn't get any sycl build. Wondering any part I am missing.
> 
> https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md#build-sycl-toolchain

Path to SYCL directory is being picked up from this CLI parameters:
```
-DLLVM_EXTERNAL_PROJECTS="llvm-spirv;sycl"
-DLLVM_EXTERNAL_SYCL_SOURCE_DIR="%SYCL_HOME%\llvm\sycl"
```

You can find out more about LLVM’s build system in the official guide https://llvm.org/docs/CMake.html


> Never mind, seems I missed typed parameter to cmake.
> 
> It appears that SYCL depends on `cl_khr_il_program` which is not supported on my local devices. Is this only for some graphics card?

SPIR-V is a way to represent device-side code in a portable format for our implementation. So, your target OpenCL runtime must support it. For OpenCL 2.1+ it is a core feature, otherwise `cl_khr_il_program` extension must present. Experimental CPU Runtime supports OpenCL 2.1 and can be used for development. Intel GPUs support OpenCL 2.1 on gen8+ (except for Atom CPUs). Both ARM and POCL have support for aforementioned extension. But I’m not sure if anyone has tried such combinations. NVidia has only support for OpenCL 1.2 and does not implement the extension. There’s also a so called host device. This is some kind of compatibility with systems without any supported OpenCL implementations. Host device is currently under development, but many things already work.
