### ISSUE TITLE
[SYCL-MLIR]: invalid codegen for `structvec.cpp` lit test

### ISSUE THREAD

**Issue by etiotto** [intel/llvm#7800]
**Describe the bug**
Attached test case contains invalid instruction: 
```
clang++ -fsycl -fsycl-device-only -O0 -w -emit-mlir t.cpp -DTY=short 2>&1 |grep error   
error: 'llvm.insertvalue' op operand #1 must be primitive LLVM type, but got 'memref<?xi16>'
```

**To Reproduce**
```
#include <initializer_list>
#include <sycl/sycl.hpp>

#ifndef TY
#define TY char
#endif

struct structvec {
  using vec2 = TY __attribute__((ext_vector_type(2)));
  vec2 v;

  structvec(std::initializer_list<TY> list) {
    for (unsigned I = 0; I < 2; ++I) {
      v[I] = *(list.begin() + I) ? -1 : 0;
    }
  }
};

SYCL_EXTERNAL structvec test_init() {
  structvec sv{0, 1};
  return sv;
}
```

Compile:
```
clang++ -fsycl -fsycl-device-only -O0 -w -emit-mlir t.cpp -DTY=short
```

**Comment by victor-eds** [comment]
This seems to be related to [this](https://github.com/intel/llvm/pull/7783#issuecomment-1353103373). I'm working on a fix.

**Comment by whitneywhtsang** [comment]
@victor-eds Currently the `convert-to-llvm-abi` pass only changes function interface (funcop, callop, returnop), are you changing it to modify operations in function body as well?  If not, then how can your change help this issue?

**Comment by victor-eds** [comment]
Sorry, misunderstood the problem. It is a completely different problem. The `llvm.insertvalue` operation cannot receive non-LLVM types.

We can either:

1. Modify the `llvm.insertvalue` operation so that it accepts non-LLVM types
2. Create our own operation that lowers to  `llvm.insertvalue`
3. Ditch `llvm.struct` and create our own struct type.

Opinion:

1. As we will find more and more cases similar to this one every time, we would tie ourselves to a change that I'm not sure it will be well received upstream.
2. This will just hide the issue IMO: we're using a low-level construct `llvm.struct` and we're paying for it
3. I think this is the ideal solution, as we would control the information held in the struct type and we could use higher-level operations. We could have this being part of a different dialect, moving lots of effort to this dialect and not losing that much work if we ever ditch `cgeist`. Con: this might be the more costly at short-time.

We might want to go with 3 in the long-run, but, if we wanna have short-results, 1 or 2 might be the way to go. In any case, these options might fix the issue, but do not hide the fact that we're violating one of MLIR's principles: do not lower too soon. What do you think? @etiotto @whitneywhtsang

**Comment by whitneywhtsang** [comment]
Another option is to generate `alloca + llvm.getelementptr + llvm.store`. This should be the fastest to implement. And it is possible that it will end up lowering to `llvm.inertvalue`. I will implement that tomorrow, and check what kind of code we have at the end of compilation. Of course we can still go for one of your options if people prefer 😄 .
I agree that we are lowering too soon in some (too many) cases, but with our resources, we may want to only change that for cases when we have performance opportunities.
