### ISSUE TITLE
[SYCL] Test includes header file that triggers deprecation warning. Please include correct header.

### ISSUE THREAD

**Issue by jbrodman** [intel/llvm#8801]
https://github.com/intel/llvm-test-suite/blob/12fdee686866fd19dd9e072a335ef58309112bb4/SYCL/OnlineCompiler/online_compiler_OpenCL.cpp#L15

**Comment by HPS-1** [comment]
This issue appears to be already fixed by the following GitHub commit:

https://github.com/intel/llvm/commit/1854b263672be6dbcc1641d1389bf7977a67df4b

Where the the problematic import statements "#include <sycl/ext/intel/online_compiler.hpp>" are replaced with the correct ones "#include <sycl/ext/intel/experimental/online_compiler.hpp>". Also the files containing these statements are moved to the main llvm repo in this commit.
