### ISSUE TITLE
Could group_local_memory_for_overwrite return pointer to type, not pointer to array of type, when given arrays?

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/llvm#9080]
Specifically, will it be alright, for example in implementation of 'group_local_memory_for_overwrite'

Instead of
```
  return reinterpret_cast<__attribute__((opencl_local)) T *>(AllocatedMem);
```
Do

```
  return reinterpret_cast<
      __attribute__((opencl_local)) typename std::remove_extent<T>::type *>(AllocatedMem);
```

❓

**Comment by Pennycook** [comment]
Could you please provide a little more context?  I'm not sure exactly what you're asking.

[sycl_ext_oneapi_local_memory](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_local_memory.asciidoc) is a _supported_ extension, which means it's implemented.  Changing the return type of one of the functions in this extension would be a breaking change, and so we're not going to make that change without a very good reason.

**Comment by CaoZhongZ** [comment]
For a allocation like this:
```
auto scratch = group_local_memory_for_overwrite<float [64]>(g);
```
We certainly will expect the return type behave like a float [], not float (*)[]. So instead of
```
auto scratch = group_local_memory_for_overwrite<float [64]>(g);
auto another_something = &*scratch;
(void)another_something[index];
```
We expect just do
```
auto* scratch = group_local_memory_for_overwrite<float [64]>(g);
(void)scratch[index];
```

**Comment by Pennycook** [comment]
The issue is that when `T` _isn't_ an array, you have to return a pointer:
```c++
float* ptr = group_local_memory_for_overwrite<float>(g);
```
We can't simply return a `float`, because we need a pointer to an allocation shared by all members of the group.  We return `T*` in both cases for consistency.

`shared_ptr` and `unique_ptr` get around this by overloading `operator []` when `T` is an array type.  We considered something similar, but ultimately decided to use the existing `multi_ptr` class rather than introduce a new SYCL-specific smart pointer.

If we _did_ change the behavior here, I think we'd want to revisit whether we should have a new SYCL-specific smart pointer (e.g. `group_ptr`), so that we can remain aligned with `make_shared` and `make_unique`.  I suspect it would take us some time to get this right, though, both because we'd have to design the new smart pointer class and because we'd have to figure out how to safely deprecate the old version of the function.

@rolandschulz, any thoughts here?

**Comment by CaoZhongZ** [comment]
Ah, no, the proposed method will return ```float *```.

```std::remove_extent``` will only affect ```[]```

**Comment by Pennycook** [comment]
I understand what you're suggesting; I'm pointing out that it is inconsistent.

In the current implementation:
- If `T` is `float` we return `multi_ptr<float>`;
- If `T` is `std::array<float, N>` we return `multi_ptr<std::array<float, N>>`; and
- If `T` is `float[64]` we return `multi_ptr<float[64]>`.

What you're suggesting would make the template specialization for `T[]` different to every other usage of the class.  I personally think that would be weird and difficult to teach.

But let's wait to hear from more of the @intel/dpcpp-specification-reviewers.

**Comment by CaoZhongZ** [comment]
Yep, that's the intention of this thread.

If really uncomfortable about the inconsistency of return type, could just use more explicit interface like 

```
auto* ptr = ya_group_local_memory_for_overwrite<float, 64>(g);
```

**Comment by Pennycook** [comment]
I've attempted to address this as part of the design for the newly proposed [sycl_ext_oneapi_work_group_local](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_local.asciidoc) extension.

Because this extension creates a `work_group_local` object, rather than relying on a free function, we didn't have the same concerns about providing implicit conversion operators.  As shown by the [usage examples](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/proposed/sycl_ext_oneapi_work_group_local.asciidoc#usage-examples), it should be possible to convert a `work_group_local<float[64]>` directly to a `float*` pointer.
