### ISSUE TITLE
cast atomic object from one type to another 

### ISSUE THREAD

**Issue by jinz2014** [intel/llvm#961]
I have a question about casting atomic objects of different types. 

How can I convert 
atomic<float, access::address_space::global_space> address
to 
atomic<uint, access::address_space::global_space> uaddress  ?

Thanks for your instruction.

**Comment by AlexeySachkov** [comment]
Hi @jinz2014, sorry for such a long delay.

Unfortunately, I don't think that there is an official way to convert one atomic object to another. Tagging @Pennycook here to comment whether it worth to add such thing into SYCL 2020 `atomic_ref`.

The only concern I have is that by allowing so, we might encourage breaking some aliasing rules, which is UB according to C++ spec

**Comment by Pennycook** [comment]
The `sycl::atomic` classes from SYCL 1.2.1 (which are deprecated in SYCL 2020) already allow these sorts of conversions.  The constructor for a `sycl::atomic<T>` accepts a `multi_ptr<PointerT>` rather than a `multi_ptr<T>`, and the description of this constructor in SYCL 2020 says:

> Permitted data types for `PointerT` are any valid scalar data type which is the same size in bytes as `T`. Constructs an instance of SYCL atomic which is associated with the pointer `ptr`, converted to a pointer of data type `T`.

SYCL 2020 and `atomic_ref` don't expose this sort of functionality, and I agree with @AlexeySachkov that it would be dangerous to introduce it.  I also hope that the introduction of native floating-point atomics via `atomic_ref` should make this sort of type-punning unnecessary...  The only use-case I'm aware of for converting between atomic types is emulation (e.g. treating a `float` as a `uint` in order to call `compare_exchange` on it), and SYCL 2020 already addresses those use-cases directly.

Does `sycl::atomic_ref<float>` address your use-case, @jinz2014?  If not, could you share a small code snippet showing what you're trying to achieve?

**Comment by jinz2014** [comment]
Yes. Thank you for your answers!
